<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/api/runtime.php';
secureCmsHeaders();$user=requireCmsAuth(false);$siteName=(string)siteConfigValue('site','name','Site');$csrf=cmsCsrfToken();$embed=(string)($_GET['embed']??'')==='1';$openKey=trim((string)($_GET['key']??''));$newOnLoad=(string)($_GET['new']??'')==='1';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="cms-csrf" content="<?=htmlspecialchars($csrf,ENT_QUOTES|ENT_HTML5,'UTF-8')?>"><title>Block Composer — AI Native CMS</title><link rel="stylesheet" href="/cms/cms.css"><link rel="stylesheet" href="/cms/editor.css"><link rel="stylesheet" href="/cms/blocks.css"><link rel="stylesheet" href="/cms/media-picker.css"><?php if($embed):?><link rel="stylesheet" href="/cms/composer-live.css"><?php endif?></head>
<body data-cms-view="blocks" data-block-open-key="<?=htmlspecialchars($openKey,ENT_QUOTES|ENT_HTML5,'UTF-8')?>" data-block-new-on-load="<?=$newOnLoad?'1':'0'?>" class="<?=$embed?'cms-embed':''?>"><?php if(!$embed):?><header class="app-header"><div><p class="eyebrow">AI Native CMS</p><strong><?=htmlspecialchars($siteName,ENT_QUOTES|ENT_HTML5,'UTF-8')?></strong></div><nav class="cms-nav" aria-label="CMS"><a href="/cms/onboarding.php">Onboarding</a><a href="/cms/blocks.php" aria-current="page">Blocks</a><a href="/cms/composer.php">Composer</a><a href="/cms/media.php">Media</a><a href="/cms/navigation.php">Navigation</a><a href="/cms/branding.php">Branding</a><a href="/cms/writing.php">Writing</a><a href="/cms/seo.php">SEO</a><a href="/cms/redirects.php">Redirects</a><a href="/cms/readiness.php">Readiness</a></nav><div class="header-actions"><span class="user-label"><?=htmlspecialchars((string)($user['displayName']??$user['username']??'Owner'),ENT_QUOTES|ENT_HTML5,'UTF-8')?></span><button id="logout" class="secondary" type="button">Sign out</button></div></header><?php endif?>
<main class="block-workspace"><aside class="block-library"><div class="toolbar"><div><p class="eyebrow">Saved presets</p><h1>Block library</h1></div><button id="new-block" type="button">New block</button></div><input id="block-filter" type="search" placeholder="Filter blocks"><button id="bootstrap-blocks" class="secondary" type="button">Import repository blocks</button><div id="block-list" class="block-list"></div></aside>
<section class="block-editor"><div id="block-empty" class="section-card"><h2>Design reusable page blocks</h2><p class="muted">Create a governed block from semantic primitives, or select a converted repository block. Presets are recipes: pages store independent placed instances.</p></div><div id="block-form" hidden><div class="toolbar"><div><p class="eyebrow" id="block-kind">Designed preset</p><h1 id="block-heading">New block</h1></div><div class="toolbar-actions"><span id="block-state" class="pill">Unsaved</span><button id="delete-block" class="secondary" type="button">Delete</button><button id="save-block" type="button">Save preset</button></div></div><section class="section-card"><div class="field-grid"><label class="field">Block name<input id="block-label" maxlength="191"></label><label class="field">Category<input id="block-category" maxlength="96"></label></div><p id="block-usage" class="muted"></p></section>
<div id="primitive-editor"><section class="section-card block-settings"><label class="field">Layout<select id="block-layout"></select></label><label class="field">Surface<select id="block-surface"></select></label><label class="field">Width<select id="block-width"></select></label><label class="field">Spacing<select id="block-spacing"></select></label></section><div class="block-design-grid"><aside class="section-card"><h2>Primitives</h2><p class="muted">Add only what this block needs.</p><div id="primitive-library" class="primitive-library"></div></aside><section class="section-card"><div class="toolbar"><div><p class="eyebrow">Live canvas</p><strong>Public-layout preview</strong></div><span id="element-count" class="pill"></span></div><div id="block-preview" class="block-preview"></div></section><aside class="section-card"><h2>Inspector</h2><div id="primitive-inspector"><p class="muted">Select an element.</p></div></aside></div></div>
<section id="converted-editor" class="section-card" hidden><h2>Converted repository structure</h2><p id="converted-note" class="muted"></p><div id="converted-preview" class="block-preview"></div><p class="muted">Its structure stays governed. Page Composer can customize exposed copy, images, and links per placement.</p></section><p id="block-status" class="status" role="status" aria-live="polite"></p></div></section></main>
<script src="/cms/media-picker.js" defer></script><script src="/cms/block-composer.js" defer></script></body></html>
