(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';const tokenRoot=document.getElementById('brand-tokens');const statusEl=document.getElementById('brand-status');const save=document.getElementById('brand-save');let state=null;
function status(message,error=false){statusEl.textContent=message||'';statusEl.dataset.error=error?'1':'0';}
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function render(){if(!state)return;document.getElementById('brand-mark').value=state.settings.identity.mark||'';document.getElementById('brand-name').value=state.settings.identity.name||'';tokenRoot.replaceChildren();for(const [key,definition] of Object.entries(state.definitions||{})){const label=document.createElement('label');label.className='field';const name=document.createElement('span');name.textContent=key;const input=document.createElement('input');input.dataset.token=key;if(definition.type==='color'){input.type='color';input.value=state.settings.tokens[key]||definition.default||'#000000';}else{input.type='number';input.min=String(definition.min);input.max=String(definition.max);input.step='any';input.value=String(state.settings.tokens[key]??definition.default??0);}const hint=document.createElement('small');hint.textContent=`${definition.css}${definition.unit?` · ${definition.unit}`:''}`;label.append(name,input,hint);tokenRoot.append(label);}save.disabled=false;}
async function load(){const data=await api('/api/cms-branding.php');state=data.branding;render();}
save?.addEventListener('click',async()=>{if(!state)return;save.disabled=true;status('Saving…');const tokens={};for(const input of tokenRoot.querySelectorAll('[data-token]'))tokens[input.dataset.token]=input.type==='number'?Number(input.value):input.value;const settings={identity:{mark:document.getElementById('brand-mark').value.trim(),name:document.getElementById('brand-name').value.trim()},tokens};try{const data=await api('/api/cms-branding.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedHash:state.hash,settings})});state=data.branding;render();status('Branding saved and projected.');}catch(e){status(e.message,true);save.disabled=false;}});
document.getElementById('logout')?.addEventListener('click',async()=>{try{await api('/api/cms-auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});
load().catch(e=>status(e.message,true));
})();
