<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/api/runtime.php';
secureCmsHeaders();$user=requireCmsAuth(false);$siteName=(string)siteConfigValue('site','name','Site');$csrf=cmsCsrfToken();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="cms-csrf" content="<?=htmlspecialchars($csrf,ENT_QUOTES|ENT_HTML5,'UTF-8')?>"><title>Page Composer — AI Native CMS</title><link rel="stylesheet" href="/cms/cms.css"><link rel="stylesheet" href="/cms/editor.css"><link rel="stylesheet" href="/cms/media-picker.css"></head>
<body data-cms-view="composer"><header class="app-header"><div><p class="eyebrow">AI Native CMS</p><strong><?=htmlspecialchars($siteName,ENT_QUOTES|ENT_HTML5,'UTF-8')?></strong></div><nav class="cms-nav" aria-label="CMS"><a href="/cms/onboarding.php">Onboarding</a><a href="/cms/pages.php">Pages</a><a href="/cms/blocks.php">Blocks</a><a href="/cms/composer.php" aria-current="page">Composer</a><a href="/cms/media.php">Media</a><a href="/cms/navigation.php">Navigation</a><a href="/cms/branding.php">Branding</a><a href="/cms/writing.php">Writing</a><a href="/cms/seo.php">SEO</a><a href="/cms/redirects.php">Redirects</a><a href="/cms/readiness.php">Readiness</a></nav><div class="header-actions"><span class="user-label"><?=htmlspecialchars((string)($user['displayName']??$user['username']??'Owner'),ENT_QUOTES|ENT_HTML5,'UTF-8')?></span><button id="logout" class="secondary" type="button">Sign out</button></div></header>
<main class="workspace"><aside class="workspace-list"><label class="field">Page<select id="composer-page"></select></label><button id="refresh-library" class="secondary" type="button">Refresh media</button><button id="bootstrap-presets" class="secondary" type="button">Import repository blocks</button><a class="button secondary" href="/cms/blocks.php">Design block / open Block Composer</a><div class="section-card"><h2>New page</h2><label class="field">Filename<input id="new-path" placeholder="services.html"></label><label class="field">Label<input id="new-label" placeholder="Services"></label><label class="field">Browser title<input id="new-title" placeholder="Services"></label><label class="field">Shell<select id="new-shell"></select></label><label class="field">Parent<select id="new-parent"></select></label><label class="check-row"><input id="new-nav" type="checkbox"> Add to primary navigation</label><button id="start-new-page" type="button">Start new page</button></div><div class="section-card"><h2>Add block</h2><label class="field">Saved preset<select id="preset-select"></select></label><button id="add-block" type="button">Add block</button></div></aside>
<section class="workspace-main"><div class="toolbar"><div><p class="eyebrow">Preset-based page composition</p><h1 id="composer-heading">Choose a page</h1></div><div class="toolbar-actions"><span id="composition-state" class="pill">Not loaded</span><button id="save-composition" type="button" disabled>Save composition</button></div></div><p class="muted">Pages place snapshots of saved block presets. Structural HTML is rendered server-side from converted governed structures or semantic primitive definitions; browser requests contain typed values only.</p><section id="page-metadata" class="section-card" hidden><h2>Page identity</h2><div class="field-grid"><label class="field">Label<input id="page-label" maxlength="191"></label><label class="field">Browser title<input id="page-title" maxlength="512"></label><label class="field">Shell<select id="page-shell"></select></label><label class="field">Parent<select id="page-parent"></select></label></div></section><div id="composition-blocks" class="revision-list" aria-live="polite"></div><p id="composer-status" class="status" role="status" aria-live="polite"></p></section></main>
<script src="/cms/media-picker.js" defer></script><script src="/cms/composer.js" defer></script></body></html>
