(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';const pageSelect=document.getElementById('composer-page'),presetSelect=document.getElementById('preset-select'),blocksEl=document.getElementById('composition-blocks'),saveBtn=document.getElementById('save-composition'),statusEl=document.getElementById('composer-status'),heading=document.getElementById('composer-heading'),stateEl=document.getElementById('composition-state'),metadataEl=document.getElementById('page-metadata'),pageLabel=document.getElementById('page-label'),pageTitle=document.getElementById('page-title'),pageShell=document.getElementById('page-shell'),pageParent=document.getElementById('page-parent'),newShell=document.getElementById('new-shell'),newParent=document.getElementById('new-parent');let presets=[],media=[],pages=[],current=null;
function status(message,error=false){statusEl.textContent=message||'';statusEl.dataset.error=error?'1':'0';}
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function option(select,value,label){const el=document.createElement('option');el.value=value;el.textContent=label;select.append(el);}function presetByKey(key){return presets.find(p=>p.key===key)||null;}
function pageOptions(select,value='',allowRoot=false,exclude=''){select.replaceChildren();if(allowRoot)option(select,'','Site root');for(const page of pages){if(page.path===exclude)continue;option(select,page.path,page.label+(page.dynamic?' · CMS page':''));}select.value=value||'';}
function mediaInput(variable,value,onChange){const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('span');label.textContent=variable.label||variable.key;const row=document.createElement('div');row.style.display='flex';row.style.gap='10px';row.style.alignItems='center';const thumb=document.createElement('img');thumb.alt='';thumb.style.cssText='width:72px;height:54px;object-fit:cover;border-radius:8px;background:#eef0f3';const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Choose image';const alt=document.createElement('input');alt.placeholder='Alt text';alt.value=value?.alt||'';let path=value?.path||'';function sync(){thumb.src=path?`/${path.replace(/^\/+/, '')}`:'';thumb.hidden=!path;}sync();button.addEventListener('click',()=>window.AINCMSMediaPicker?.open({items:media,value:path,onSelect:(item,nextPath)=>{path=nextPath;if(!alt.value)alt.value=item?.alt||'';sync();onChange({path,alt:alt.value});}}));alt.addEventListener('input',()=>onChange({path,alt:alt.value}));row.append(thumb,button);wrap.append(label,row,alt);return wrap;}
function variableInput(variable,value,onChange){if(variable.type==='media')return mediaInput(variable,value,onChange);const wrap=document.createElement('label');wrap.className='field';const name=document.createElement('span');name.textContent=variable.label||variable.key;wrap.append(name);if(variable.type==='richtext'){const input=document.createElement('textarea');input.rows=3;input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>onChange(input.value));wrap.append(input);}else{const input=document.createElement('input');input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>onChange(input.value));wrap.append(input);}return wrap;}
function render(){blocksEl.replaceChildren();if(!current){saveBtn.disabled=true;metadataEl.hidden=true;return;}heading.textContent=current.label||current.path;stateEl.textContent=current.isNew?'New page':(current.composed?'Composed':'Using repository page');saveBtn.disabled=false;saveBtn.textContent=current.isNew?'Create page':'Save composition';metadataEl.hidden=false;pageLabel.value=current.label||'';pageTitle.value=current.title||'';pageOptions(pageShell,current.shellPath||current.path,false,current.isNew?current.path:'');pageOptions(pageParent,current.parentPath||'',true,current.path);current.blocks.forEach((block,index)=>{const preset=presetByKey(block.presetKey);const card=document.createElement('section');card.className='section-card';const row=document.createElement('div');row.className='toolbar';const title=document.createElement('strong');title.textContent=preset?.label||block.label||block.presetKey;row.append(title);const actions=document.createElement('div');actions.className='toolbar-actions';for(const [text,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=text;b.disabled=index+delta<0||index+delta>=current.blocks.length;b.addEventListener('click',()=>{const next=index+delta;[current.blocks[index],current.blocks[next]]=[current.blocks[next],current.blocks[index]];render();});actions.append(b);}const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Remove';remove.addEventListener('click',()=>{current.blocks.splice(index,1);render();});actions.append(remove);row.append(actions);card.append(row);const vars=preset?.variables||block.variables||[];for(const variable of vars){const key=variable.key;const value=Object.prototype.hasOwnProperty.call(block.values||{},key)?block.values[key]:variable.default;card.append(variableInput(variable,value,next=>{block.values=block.values||{};block.values[key]=next;}));}blocksEl.append(card);});}
function fillLists(){pageSelect.replaceChildren();for(const page of pages)option(pageSelect,page.path,page.label+(page.composed?' · composed':''));presetSelect.replaceChildren();for(const p of presets)option(presetSelect,p.key,`${p.category} · ${p.label}`);pageOptions(newShell,'',false);pageOptions(newParent,'',true);}
async function loadIndex(preferred=''){const data=await api('/api/cms-composer.php');presets=data.presets||[];media=data.media||[];pages=data.pages||[];fillLists();if(preferred&&pages.some(p=>p.path===preferred))pageSelect.value=preferred;if(pageSelect.value)await loadPage(pageSelect.value);}
async function loadPage(path){status('Loading…');try{const data=await api(`/api/cms-composer.php?path=${encodeURIComponent(path)}`);presets=data.presets||presets;media=data.media||media;current=data.page;current.isNew=false;render();status('');}catch(e){status(e.message,true);}}
pageSelect?.addEventListener('change',()=>loadPage(pageSelect.value));document.getElementById('add-block')?.addEventListener('click',()=>{if(!current)return;const preset=presetByKey(presetSelect.value);if(!preset)return;const instance=`blk-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;current.blocks.push({presetKey:preset.key,instanceId:instance,values:structuredClone(preset.defaults||{})});render();});
document.getElementById('start-new-page')?.addEventListener('click',()=>{const path=document.getElementById('new-path').value.trim(),label=document.getElementById('new-label').value.trim(),title=document.getElementById('new-title').value.trim(),shell=newShell.value,parent=newParent.value||null;if(!path||!label||!title||!shell){status('Filename, label, title, and shell are required.',true);return;}current={path,label,title,shellPath:shell,parentPath:parent,hash:'none',composed:true,isNew:true,includeInNavigation:document.getElementById('new-nav').checked,blocks:[]};render();status('Add at least one saved block preset, then create the page.');});
document.getElementById('refresh-library')?.addEventListener('click',async()=>{status('Refreshing media…');try{const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});presets=data.presets||presets;media=data.media||[];fillLists();if(current&&!current.isNew)await loadPage(current.path);else render();status('Media catalog refreshed.');}catch(e){status(e.message,true);}});
document.getElementById('bootstrap-presets')?.addEventListener('click',async()=>{status('Importing governed repository blocks…');try{const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'bootstrapPresets'})});presets=data.presets||[];media=data.media||media;fillLists();render();status('Saved block preset library is ready.');}catch(e){status(e.message,true);}});
saveBtn?.addEventListener('click',async()=>{if(!current)return;saveBtn.disabled=true;status(current.isNew?'Creating…':'Saving…');try{const items=current.blocks.map(b=>({presetKey:b.presetKey,instanceId:b.instanceId,values:b.values||{}}));const metadata={label:pageLabel.value.trim(),title:pageTitle.value.trim(),shellPath:pageShell.value,parentPath:pageParent.value||null};const payload=current.isNew?{action:'create',path:current.path,label:metadata.label,title:metadata.title,shellPath:metadata.shellPath,parentPath:metadata.parentPath,includeInNavigation:!!current.includeInNavigation,navigationLabel:metadata.label,items}:{action:'save',path:current.path,expectedHash:current.hash,...metadata,items};const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});current=data.page;current.isNew=false;await loadIndex(current.path);status(payload.action==='create'?'Page created and projected.':'Composition saved and projected.');}catch(e){status(e.message,true);saveBtn.disabled=false;}});
document.getElementById('logout')?.addEventListener('click',async()=>{try{await api('/api/cms-auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});loadIndex().catch(e=>status(e.message,true));
})();
