(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';
const pageSelect=document.getElementById('composer-page');const templateSelect=document.getElementById('template-select');const blocksEl=document.getElementById('composition-blocks');const saveBtn=document.getElementById('save-composition');const statusEl=document.getElementById('composer-status');const heading=document.getElementById('composer-heading');const stateEl=document.getElementById('composition-state');const metadataEl=document.getElementById('page-metadata');
const pageLabel=document.getElementById('page-label');const pageTitle=document.getElementById('page-title');const pageShell=document.getElementById('page-shell');const pageParent=document.getElementById('page-parent');const newShell=document.getElementById('new-shell');const newParent=document.getElementById('new-parent');
let templates=[];let media=[];let pages=[];let current=null;
function status(message,error=false){statusEl.textContent=message||'';statusEl.dataset.error=error?'1':'0';}
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function option(select,value,label){const el=document.createElement('option');el.value=value;el.textContent=label;select.append(el);}
function templateByKey(key){return templates.find(t=>t.key===key)||null;}
function mediaOptions(select,value=''){option(select,'','No image');for(const item of media)option(select,item.path,item.title?`${item.title} — ${item.path}`:item.path);select.value=value||'';}
function pageOptions(select,value='',allowRoot=false,exclude=''){select.replaceChildren();if(allowRoot)option(select,'','Site root');for(const page of pages){if(page.path===exclude)continue;option(select,page.path,page.label+(page.dynamic?' · CMS page':''));}select.value=value||'';}
function variableInput(variable,value,onChange){const wrap=document.createElement('label');wrap.className='field';const name=document.createElement('span');name.textContent=variable.label||variable.key;wrap.append(name);if(variable.type==='richtext'){const input=document.createElement('textarea');input.rows=3;input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>onChange(input.value));wrap.append(input);}else if(variable.type==='media'){const select=document.createElement('select');const alt=document.createElement('input');alt.placeholder='Alt text';alt.value=value?.alt||'';mediaOptions(select,value?.path||'');select.addEventListener('change',()=>onChange({path:select.value,alt:alt.value}));alt.addEventListener('input',()=>onChange({path:select.value,alt:alt.value}));wrap.append(select,alt);}else{const input=document.createElement('input');input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>onChange(input.value));wrap.append(input);}return wrap;}
function render(){blocksEl.replaceChildren();if(!current){saveBtn.disabled=true;metadataEl.hidden=true;return;}heading.textContent=current.label||current.path;stateEl.textContent=current.isNew?'New page':(current.composed?'Composed':'Using page blocks');saveBtn.disabled=false;saveBtn.textContent=current.isNew?'Create page':'Save composition';metadataEl.hidden=false;pageLabel.value=current.label||'';pageTitle.value=current.title||'';pageOptions(pageShell,current.shellPath||current.path,false,current.isNew?current.path:'');pageOptions(pageParent,current.parentPath||'',true,current.path);
    current.blocks.forEach((block,index)=>{const template=templateByKey(block.templateKey);const card=document.createElement('section');card.className='section-card';const row=document.createElement('div');row.className='toolbar';const title=document.createElement('strong');title.textContent=template?.label||block.label||block.templateKey;row.append(title);const actions=document.createElement('div');actions.className='toolbar-actions';for(const [label,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=label;b.disabled=index+delta<0||index+delta>=current.blocks.length;b.addEventListener('click',()=>{const next=index+delta;[current.blocks[index],current.blocks[next]]=[current.blocks[next],current.blocks[index]];render();});actions.append(b);}const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Remove';remove.addEventListener('click',()=>{current.blocks.splice(index,1);render();});actions.append(remove);row.append(actions);card.append(row);const vars=template?.variables||block.variables||[];for(const variable of vars){const key=variable.key;const value=Object.prototype.hasOwnProperty.call(block.values||{},key)?block.values[key]:variable.default;card.append(variableInput(variable,value,next=>{block.values=block.values||{};block.values[key]=next;}));}blocksEl.append(card);});}
function fillLists(){pageSelect.replaceChildren();for(const page of pages)option(pageSelect,page.path,page.label+(page.composed?' · composed':''));templateSelect.replaceChildren();for(const t of templates)option(templateSelect,t.key,`${t.category} · ${t.label}`);pageOptions(newShell,'',false);pageOptions(newParent,'',true);}
async function loadIndex(preferred=''){const data=await api('/api/cms-composer.php');templates=data.templates||[];media=data.media||[];pages=data.pages||[];fillLists();if(preferred&&pages.some(p=>p.path===preferred))pageSelect.value=preferred;if(pageSelect.value)await loadPage(pageSelect.value);}
async function loadPage(path){status('Loading…');try{const data=await api(`/api/cms-composer.php?path=${encodeURIComponent(path)}`);templates=data.templates||templates;media=data.media||media;current=data.page;current.isNew=false;render();status('');}catch(e){status(e.message,true);}}
pageSelect?.addEventListener('change',()=>loadPage(pageSelect.value));
document.getElementById('add-block')?.addEventListener('click',()=>{if(!current)return;const template=templateByKey(templateSelect.value);if(!template)return;const instance=`blk-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;current.blocks.push({templateKey:template.key,instanceId:instance,values:structuredClone(template.defaults||{})});render();});
document.getElementById('start-new-page')?.addEventListener('click',()=>{const path=document.getElementById('new-path').value.trim();const label=document.getElementById('new-label').value.trim();const title=document.getElementById('new-title').value.trim();const shell=newShell.value;const parent=newParent.value||null;if(!path||!label||!title||!shell){status('Filename, label, title, and shell are required.',true);return;}current={path,label,title,shellPath:shell,parentPath:parent,hash:'none',composed:true,isNew:true,includeInNavigation:document.getElementById('new-nav').checked,blocks:[]};render();status('Add at least one trusted block, then create the page.');});
document.getElementById('refresh-library')?.addEventListener('click',async()=>{status('Refreshing…');try{const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});templates=data.templates||[];media=data.media||[];fillLists();if(current&&!current.isNew)await loadPage(current.path);else render();status('Template and media catalogs refreshed.');}catch(e){status(e.message,true);}});
saveBtn?.addEventListener('click',async()=>{if(!current)return;saveBtn.disabled=true;status(current.isNew?'Creating…':'Saving…');try{const items=current.blocks.map(b=>({templateKey:b.templateKey,instanceId:b.instanceId,values:b.values||{}}));const metadata={label:pageLabel.value.trim(),title:pageTitle.value.trim(),shellPath:pageShell.value,parentPath:pageParent.value||null};const payload=current.isNew?{action:'create',path:current.path,label:metadata.label,title:metadata.title,shellPath:metadata.shellPath,parentPath:metadata.parentPath,includeInNavigation:!!current.includeInNavigation,navigationLabel:metadata.label,items}:{action:'save',path:current.path,expectedHash:current.hash,...metadata,items};const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});current=data.page;current.isNew=false;await loadIndex(current.path);status(payload.action==='create'?'Page created and projected.':'Composition saved and projected.');}catch(e){status(e.message,true);saveBtn.disabled=false;}});
document.getElementById('logout')?.addEventListener('click',async()=>{try{await api('/api/cms-auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});
loadIndex().catch(e=>status(e.message,true));
})();
