(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';
const pageSelect=document.getElementById('composer-page');
const templateSelect=document.getElementById('template-select');
const blocksEl=document.getElementById('composition-blocks');
const saveBtn=document.getElementById('save-composition');
const statusEl=document.getElementById('composer-status');
const heading=document.getElementById('composer-heading');
const stateEl=document.getElementById('composition-state');
let templates=[];let media=[];let current=null;
function status(message,error=false){statusEl.textContent=message||'';statusEl.dataset.error=error?'1':'0';}
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function option(select,value,label){const el=document.createElement('option');el.value=value;el.textContent=label;select.append(el);}
function templateByKey(key){return templates.find(t=>t.key===key)||null;}
function mediaOptions(select,value=''){option(select,'','No image');for(const item of media)option(select,item.path,item.title?`${item.title} — ${item.path}`:item.path);select.value=value||'';}
function variableInput(variable,value,onChange){const wrap=document.createElement('label');wrap.className='field';const name=document.createElement('span');name.textContent=variable.label||variable.key;wrap.append(name);if(variable.type==='richtext'){const input=document.createElement('textarea');input.rows=3;input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>onChange(input.value));wrap.append(input);}else if(variable.type==='media'){const select=document.createElement('select');mediaOptions(select,value?.path||'');select.addEventListener('change',()=>onChange({path:select.value,alt:alt.value}));wrap.append(select);const alt=document.createElement('input');alt.placeholder='Alt text';alt.value=value?.alt||'';alt.addEventListener('input',()=>onChange({path:select.value,alt:alt.value}));wrap.append(alt);}else{const input=document.createElement('input');input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>onChange(input.value));wrap.append(input);}return wrap;}
function render(){blocksEl.replaceChildren();if(!current){saveBtn.disabled=true;return;}heading.textContent=current.label||current.path;stateEl.textContent=current.composed?'Composed':'Using page blocks';saveBtn.disabled=false;current.blocks.forEach((block,index)=>{const template=templateByKey(block.templateKey);const card=document.createElement('section');card.className='section-card';const row=document.createElement('div');row.className='toolbar';const title=document.createElement('strong');title.textContent=template?.label||block.label||block.templateKey;row.append(title);const actions=document.createElement('div');actions.className='toolbar-actions';for(const [label,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=label;b.disabled=index+delta<0||index+delta>=current.blocks.length;b.addEventListener('click',()=>{const next=index+delta;[current.blocks[index],current.blocks[next]]=[current.blocks[next],current.blocks[index]];render();});actions.append(b);}const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Remove';remove.addEventListener('click',()=>{current.blocks.splice(index,1);render();});actions.append(remove);row.append(actions);card.append(row);const vars=template?.variables||block.variables||[];for(const variable of vars){const key=variable.key;const value=Object.prototype.hasOwnProperty.call(block.values||{},key)?block.values[key]:variable.default;card.append(variableInput(variable,value,next=>{block.values=block.values||{};block.values[key]=next;}));}blocksEl.append(card);});}
async function loadIndex(){const data=await api('/api/cms-composer.php');templates=data.templates||[];media=data.media||[];pageSelect.replaceChildren();for(const page of data.pages||[])option(pageSelect,page.path,page.label+(page.composed?' · composed':''));templateSelect.replaceChildren();for(const t of templates)option(templateSelect,t.key,`${t.category} · ${t.label}`);if(pageSelect.value)await loadPage(pageSelect.value);}
async function loadPage(path){status('Loading…');try{const data=await api(`/api/cms-composer.php?path=${encodeURIComponent(path)}`);templates=data.templates||templates;media=data.media||media;current=data.page;render();status('');}catch(e){status(e.message,true);}}
pageSelect?.addEventListener('change',()=>loadPage(pageSelect.value));
document.getElementById('add-block')?.addEventListener('click',()=>{if(!current)return;const template=templateByKey(templateSelect.value);if(!template)return;const instance=`blk-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;current.blocks.push({templateKey:template.key,instanceId:instance,values:structuredClone(template.defaults||{})});render();});
document.getElementById('refresh-library')?.addEventListener('click',async()=>{status('Refreshing…');try{const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});templates=data.templates||[];media=data.media||[];templateSelect.replaceChildren();for(const t of templates)option(templateSelect,t.key,`${t.category} · ${t.label}`);if(current)await loadPage(current.path);status('Template and media catalogs refreshed.');}catch(e){status(e.message,true);}});
saveBtn?.addEventListener('click',async()=>{if(!current)return;saveBtn.disabled=true;status('Saving…');try{const items=current.blocks.map(b=>({templateKey:b.templateKey,instanceId:b.instanceId,values:b.values||{}}));const data=await api('/api/cms-composer.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',path:current.path,expectedHash:current.hash,items})});current=data.page;render();status('Composition saved and projected.');}catch(e){status(e.message,true);saveBtn.disabled=false;}});
document.getElementById('logout')?.addEventListener('click',async()=>{try{await api('/api/cms-auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});
loadIndex().catch(e=>status(e.message,true));
})();
