<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/api/runtime.php';
secureCmsHeaders();$user=requireCmsAuth(false);$siteName=(string)siteConfigValue('site','name','Site');$csrf=cmsCsrfToken();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="cms-csrf" content="<?=htmlspecialchars($csrf,ENT_QUOTES|ENT_HTML5,'UTF-8')?>"><title>Page Composer — AI Native CMS</title><link rel="stylesheet" href="/cms/cms.css"><link rel="stylesheet" href="/cms/editor.css"><link rel="stylesheet" href="/cms/media-picker.css"><link rel="stylesheet" href="/cms/composer-live.css"></head>
<body data-cms-view="composer"><header class="app-header"><div><p class="eyebrow">AI Native CMS</p><strong><?=htmlspecialchars($siteName,ENT_QUOTES|ENT_HTML5,'UTF-8')?></strong></div><nav class="cms-nav" aria-label="CMS"><a href="/cms/onboarding.php">Onboarding</a><a href="/cms/blocks.php">Blocks</a><a href="/cms/composer.php" aria-current="page">Composer</a><a href="/cms/media.php">Media</a><a href="/cms/navigation.php">Navigation</a><a href="/cms/branding.php">Branding</a><a href="/cms/writing.php">Writing</a><a href="/cms/seo.php">SEO</a><a href="/cms/redirects.php">Redirects</a><a href="/cms/readiness.php">Readiness</a></nav><div class="header-actions"><span class="user-label"><?=htmlspecialchars((string)($user['displayName']??$user['username']??'Owner'),ENT_QUOTES|ENT_HTML5,'UTF-8')?></span><button id="logout" class="secondary" type="button">Sign out</button></div></header>
<main class="composer-live-layout">
<aside class="composer-sidebar"><div class="composer-sidebar-head"><div><p class="eyebrow">Pages</p><h1>Page Composer</h1></div></div><input id="composer-page-filter" type="search" placeholder="Filter pages" aria-label="Filter pages"><div id="composer-pages" class="composer-page-list" aria-live="polite"></div><div class="composer-sidebar-actions"><button id="new-page" type="button">New page</button><button id="design-block" class="secondary" type="button">Design block</button><button id="refresh-library" class="secondary" type="button">Refresh media</button></div></aside>
<section class="composer-live-main"><div id="composer-context" class="composer-live-context" hidden><div><span>Editing</span><strong id="composer-current">Choose a page</strong><small id="composer-status" role="status" aria-live="polite"></small></div><div class="composer-context-actions"><button id="page-settings" class="secondary" type="button">Page settings</button><button id="add-block" class="secondary" type="button">Add block</button><button id="save-composition" type="button" disabled>Save page</button></div></div>
<div id="copy-toolbar" class="composer-copy-toolbar" hidden><button type="button" class="secondary" data-cmd="bold"><strong>B</strong></button><button type="button" class="secondary" data-cmd="italic"><em>I</em></button><button type="button" class="secondary" data-cmd="createLink">Link</button><button type="button" class="secondary" data-cmd="unlink">Unlink</button><button type="button" class="secondary" data-cmd="removeFormat">Clear format</button><span>Text edits and block structure save together.</span></div>
<div id="composer-empty" class="composer-live-empty"><div><strong>Select a page to begin.</strong><p>The public page opens in its real layout. Edit highlighted copy directly; select a block to move, duplicate, remove, or insert another block beside it.</p></div></div>
<div id="composer-frame-wrap" class="composer-live-frame-wrap" hidden><iframe id="composer-frame" title="Editable page preview" sandbox="allow-same-origin"></iframe></div>
<section id="selected-panel" class="composer-selected-panel" hidden><div class="composer-selected-summary"><p class="eyebrow">Selected block</p><strong id="selected-label"></strong><small id="selected-detail"></small></div><div id="selected-fields" class="composer-selected-fields"></div></section></section>
</main>
<dialog id="settings-dialog" class="composer-dialog"><div class="dialog-head"><div><p class="eyebrow">Page settings</p><h2>Identity and hierarchy</h2></div><button type="button" class="secondary" data-close-dialog="settings-dialog" aria-label="Close">×</button></div><div class="field-grid"><label class="field">CMS label<input id="page-label" maxlength="191"></label><label class="field">Browser title<input id="page-title" maxlength="512"></label><label class="field">Shell<select id="page-shell"></select><small>Header, scripts, and footer come from this managed page.</small></label><label class="field">Parent<select id="page-parent"></select><small>Hierarchy is independent of filename.</small></label></div><div class="toolbar-actions" style="justify-content:flex-end;margin-top:1rem"><button type="button" data-close-dialog="settings-dialog">Done</button></div></dialog>
<dialog id="add-dialog" class="composer-dialog"><div class="dialog-head"><div><p class="eyebrow">Add page block</p><h2>Choose what comes next</h2></div><button type="button" class="secondary" data-close-dialog="add-dialog" aria-label="Close">×</button></div><div class="composer-add-head"><input id="preset-filter" type="search" placeholder="Find a saved block"><button id="design-block-from-add" type="button">Design new block</button></div><div id="preset-picker" class="composer-preset-picker"></div></dialog>
<dialog id="block-dialog" class="composer-block-dialog"><div class="composer-block-dialog-head"><div><p class="eyebrow">Block Composer</p><strong id="block-dialog-title">Design a block</strong><small>Preset edits affect future placements only unless you add the saved block here.</small></div><button id="block-dialog-close" type="button" class="secondary" aria-label="Close">×</button></div><iframe id="block-frame" title="Inline Block Composer"></iframe></dialog>
<dialog id="new-dialog" class="composer-dialog"><div class="dialog-head"><div><p class="eyebrow">New page</p><h2>Create the page in context</h2></div><button type="button" class="secondary" data-close-dialog="new-dialog" aria-label="Close">×</button></div><div class="field-grid"><label class="field">CMS label<input id="new-label" placeholder="Services"></label><label class="field">Filename<input id="new-path" placeholder="services.html" pattern="[a-z0-9][a-z0-9-]*\.html"></label><label class="field wide">Browser title<input id="new-title" placeholder="Services"></label><label class="field">Starting shell<select id="new-shell"></select></label><label class="field">Parent page<select id="new-parent"></select></label><label class="check-row wide"><input id="new-nav" type="checkbox"> Add this page to primary navigation</label><label id="new-nav-label-wrap" class="field wide" hidden>Navigation label<input id="new-nav-label" placeholder="Services"></label></div><div class="toolbar-actions" style="justify-content:flex-end;margin-top:1rem"><button type="button" class="secondary" data-close-dialog="new-dialog">Cancel</button><button id="create-page" type="button">Create page</button></div></dialog>
<script src="/cms/media-picker.js" defer></script><script src="/cms/composer.js" defer></script></body></html>
