(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';const list=document.getElementById('media-list');const statusEl=document.getElementById('media-status');const countEl=document.getElementById('media-count');let items=[];
function status(message,error=false){statusEl.textContent=message||'';statusEl.dataset.error=error?'1':'0';}
async function request(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function field(label,value,max=0){const wrap=document.createElement('label');wrap.className='field';const span=document.createElement('span');span.textContent=label;const input=document.createElement(label==='Caption'?'textarea':'input');if(max)input.maxLength=max;input.value=value||'';wrap.append(span,input);return {wrap,input};}
function render(){list.replaceChildren();countEl.textContent=`${items.length} asset${items.length===1?'':'s'}`;for(const item of items){const card=document.createElement('section');card.className='section-card';const title=document.createElement('strong');title.textContent=item.title||item.path;const meta=document.createElement('p');meta.className='muted';meta.textContent=`${item.path} · ${item.mime}${item.width&&item.height?` · ${item.width}×${item.height}`:''}`;card.append(title,meta);if((item.mime||'').startsWith('image/')){const img=document.createElement('img');img.src='/'+item.path.replace(/^\/+/, '');img.alt=item.alt||'';img.loading='lazy';img.style.maxWidth='240px';img.style.maxHeight='160px';card.append(img);}const titleField=field('Title',item.title,191);const altField=field('Alt text',item.alt,1000);const captionField=field('Caption',item.caption);captionField.input.rows=2;const save=document.createElement('button');save.type='button';save.textContent='Save metadata';save.addEventListener('click',async()=>{save.disabled=true;status('Saving…');try{const data=await request('/api/cms-media.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update',key:item.key,title:titleField.input.value,alt:altField.input.value,caption:captionField.input.value})});Object.assign(item,data.item);render();status('Media metadata saved.');}catch(e){status(e.message,true);save.disabled=false;}});card.append(titleField.wrap,altField.wrap,captionField.wrap,save);list.append(card);}}
async function load(){const data=await request('/api/cms-media.php');items=data.items||[];render();}
document.getElementById('refresh-media')?.addEventListener('click',async()=>{status('Refreshing…');try{const data=await request('/api/cms-media.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});items=data.items||[];render();status('Media catalog refreshed.');}catch(e){status(e.message,true);}});
document.getElementById('media-upload')?.addEventListener('submit',async event=>{event.preventDefault();const file=document.getElementById('media-file').files?.[0];if(!file)return;const form=new FormData();form.append('file',file);form.append('title',document.getElementById('upload-title').value);form.append('alt',document.getElementById('upload-alt').value);form.append('caption',document.getElementById('upload-caption').value);status('Uploading…');try{const data=await request('/api/cms-media.php',{method:'POST',body:form});items=data.items||items;render();event.target.reset();status('Image uploaded.');}catch(e){status(e.message,true);}});
document.getElementById('logout')?.addEventListener('click',async()=>{try{await request('/api/cms-auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});
load().catch(e=>status(e.message,true));
})();
