<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/api/runtime.php';
secureCmsHeaders();$user=requireCmsAuth(false);$siteName=(string)siteConfigValue('site','name','Site');$csrf=cmsCsrfToken();
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="cms-csrf" content="<?=htmlspecialchars($csrf,ENT_QUOTES|ENT_HTML5,'UTF-8')?>"><title>Navigation — AI Native CMS</title><link rel="stylesheet" href="/cms/cms.css"><link rel="stylesheet" href="/cms/editor.css"></head>
<body data-cms-view="navigation">
<header class="app-header"><div><p class="eyebrow">AI Native CMS</p><strong><?=htmlspecialchars($siteName,ENT_QUOTES|ENT_HTML5,'UTF-8')?></strong></div><nav class="cms-nav" aria-label="CMS"><a href="/cms/onboarding.php">Onboarding</a><a href="/cms/pages.php">Pages</a><a href="/cms/composer.php">Composer</a><a href="/cms/media.php">Media</a><a href="/cms/navigation.php" aria-current="page">Navigation</a><a href="/cms/branding.php">Branding</a><a href="/cms/writing.php">Writing</a><a href="/cms/seo.php">SEO</a><a href="/cms/redirects.php">Redirects</a><a href="/cms/readiness.php">Readiness</a></nav><div class="header-actions"><span class="user-label"><?=htmlspecialchars((string)($user['displayName']??$user['username']??'Owner'),ENT_QUOTES|ENT_HTML5,'UTF-8')?></span><button id="logout" class="secondary" type="button">Sign out</button></div></header>
<main class="workspace"><aside class="workspace-list"><div class="section-card"><h2>Add item</h2><label class="field">Label<input id="nav-new-label" maxlength="80"></label><label class="field">Destination<select id="nav-page"></select></label><button id="nav-add" type="button">Add item</button></div></aside><section class="workspace-main"><div class="toolbar"><div><p class="eyebrow">Canonical site-wide state</p><h1>Primary navigation</h1></div><button id="nav-save" type="button" disabled>Save navigation</button></div><p class="muted">Order, labels, enabled state, and destinations are canonical. Projection replaces only the contents of <code>#site-nav</code> on public HTML pages.</p><div id="nav-items" class="revision-list" aria-live="polite"></div><p id="nav-status" class="status" role="status" aria-live="polite"></p></section></main>
<script src="/cms/navigation.js" defer></script></body></html>
