(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';const list=document.getElementById('nav-items');const save=document.getElementById('nav-save');const statusEl=document.getElementById('nav-status');const pageSelect=document.getElementById('nav-page');let items=[];let hash='';let pages=[];
function status(message,error=false){statusEl.textContent=message||'';statusEl.dataset.error=error?'1':'0';}
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function option(value,label){const el=document.createElement('option');el.value=value;el.textContent=label;pageSelect.append(el);}
function render(){list.replaceChildren();save.disabled=false;items.forEach((item,index)=>{const card=document.createElement('section');card.className='section-card';const row=document.createElement('div');row.className='toolbar';const label=document.createElement('input');label.value=item.label||'';label.maxLength=80;label.setAttribute('aria-label','Navigation label');label.addEventListener('input',()=>item.label=label.value);const actions=document.createElement('div');actions.className='toolbar-actions';for(const [text,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=text;b.disabled=index+delta<0||index+delta>=items.length;b.addEventListener('click',()=>{const next=index+delta;[items[index],items[next]]=[items[next],items[index]];render();});actions.append(b);}const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Remove';remove.addEventListener('click',()=>{items.splice(index,1);render();});actions.append(remove);row.append(label,actions);const href=document.createElement('input');href.value=item.href||'';href.maxLength=512;href.setAttribute('aria-label','Navigation destination');href.addEventListener('input',()=>item.href=href.value);const enabled=document.createElement('label');enabled.className='check-row';const check=document.createElement('input');check.type='checkbox';check.checked=item.enabled!==false;check.addEventListener('change',()=>item.enabled=check.checked);enabled.append(check,document.createTextNode(' Enabled'));card.append(row,href,enabled);list.append(card);});}
async function load(){const data=await api('/api/cms-navigation.php');items=data.navigation?.items||[];hash=data.navigation?.hash||'';pages=data.pages||[];pageSelect.replaceChildren();for(const page of pages)option(page.href,page.label);render();}
document.getElementById('nav-add')?.addEventListener('click',()=>{const label=document.getElementById('nav-new-label').value.trim();const href=pageSelect.value;if(!label||!href){status('Choose a label and destination.',true);return;}items.push({id:`page-${Math.random().toString(36).slice(2,10)}`,label,href,enabled:true});document.getElementById('nav-new-label').value='';render();});
save?.addEventListener('click',async()=>{save.disabled=true;status('Saving…');try{const data=await api('/api/cms-navigation.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedHash:hash,items})});items=data.navigation.items||items;hash=data.navigation.hash||hash;render();status('Navigation saved and projected.');}catch(e){status(e.message,true);save.disabled=false;}});
document.getElementById('logout')?.addEventListener('click',async()=>{try{await api('/api/cms-auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});
load().catch(e=>status(e.message,true));
})();
