<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/api/runtime.php';
secureCmsHeaders();$user=requireCmsAuth(false);$siteName=(string)siteConfigValue('site','name','Site');$csrf=cmsCsrfToken();
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="cms-csrf" content="<?=htmlspecialchars($csrf,ENT_QUOTES|ENT_HTML5,'UTF-8')?>"><title>Redirects — AI Native CMS</title><link rel="stylesheet" href="/cms/cms.css"><link rel="stylesheet" href="/cms/editor.css"></head>
<body data-cms-view="redirects">
<header class="app-header"><div><p class="eyebrow">AI Native CMS</p><strong><?=htmlspecialchars($siteName,ENT_QUOTES|ENT_HTML5,'UTF-8')?></strong></div><nav class="cms-nav" aria-label="CMS"><a href="/cms/onboarding.php">Onboarding</a><a href="/cms/blocks.php">Blocks</a><a href="/cms/composer.php">Composer</a><a href="/cms/media.php">Media</a><a href="/cms/navigation.php">Navigation</a><a href="/cms/branding.php">Branding</a><a href="/cms/writing.php">Writing</a><a href="/cms/seo.php">SEO</a><a href="/cms/redirects.php" aria-current="page">Redirects</a><a href="/cms/readiness.php">Readiness</a></nav><div class="header-actions"><span class="user-label"><?=htmlspecialchars((string)($user['displayName']??$user['username']??'Owner'),ENT_QUOTES|ENT_HTML5,'UTF-8')?></span><button id="logout" class="secondary" type="button">Sign out</button></div></header>
<main class="workspace"><aside class="workspace-list"><div class="toolbar"><div><p class="eyebrow">Canonical URL state</p><h1>Redirects</h1></div><button id="redirect-new" type="button">New</button></div><label class="field">Filter<input id="redirect-filter" type="search" placeholder="/old-path/"></label><div id="redirect-summary" class="muted"></div><div id="redirect-list" class="revision-list" aria-live="polite"></div></aside><section class="workspace-main"><div class="toolbar"><div><p class="eyebrow" id="redirect-provenance">MANUAL</p><h2 id="redirect-heading">New redirect</h2></div><span id="redirect-state" class="muted"></span></div><p class="muted">Redirects are canonical records projected into a database-free runtime map. Configured system aliases are visible but read-only.</p><form id="redirect-form"><input type="hidden" id="redirect-id" value="0"><div class="section-card"><label class="field">Old path<input id="redirect-source" required placeholder="/old-page/"></label><label class="field">New path<input id="redirect-target" required placeholder="/new-page/"></label><label class="field">HTTP status<select id="redirect-status"><option value="301">301 permanent</option><option value="308">308 permanent</option><option value="302">302 temporary</option><option value="307">307 temporary</option></select></label><label class="check-row"><input id="redirect-query" type="checkbox" checked> Preserve incoming query string</label><label class="check-row"><input id="redirect-active" type="checkbox" checked> Active</label><label class="field">Note<textarea id="redirect-note" rows="4" maxlength="1000"></textarea></label></div><div class="toolbar-actions"><button id="redirect-save" type="submit">Save redirect</button><button id="redirect-delete" class="secondary" type="button" hidden>Delete</button></div></form><p id="redirect-message" class="status" role="status" aria-live="polite"></p></section></main>
<script src="/cms/redirects.js" defer></script></body></html>
