(()=>{
'use strict';
const csrf=document.querySelector('meta[name="cms-csrf"]')?.content||'';const list=document.getElementById('redirect-list');const summary=document.getElementById('redirect-summary');const filter=document.getElementById('redirect-filter');const form=document.getElementById('redirect-form');const message=document.getElementById('redirect-message');let rows=[];let selected=null;
const el=id=>document.getElementById(id);function say(text,error=false){message.textContent=text||'';message.dataset.error=error?'1':'0';}
async function api(options={}){const response=await fetch('/api/cms-redirects.php',{credentials:'same-origin',...options,headers:{...(options.headers||{}),'X-CMS-CSRF':csrf}});let data={};try{data=await response.json();}catch(_e){}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function setEditor(row=null){selected=row;const readOnly=!!row?.readOnly;el('redirect-id').value=String(row?.id||0);el('redirect-source').value=row?.source||'';el('redirect-target').value=row?.target||'';el('redirect-status').value=String(row?.status||301);el('redirect-query').checked=row?.preserveQuery!==false;el('redirect-active').checked=row?.active!==false;el('redirect-note').value=row?.note||'';el('redirect-heading').textContent=row?.source||'New redirect';el('redirect-provenance').textContent=(row?.managedBy||'manual').toUpperCase();el('redirect-state').textContent=readOnly?'Read only':(row?.active===false?'Inactive':'Editable');for(const id of ['redirect-source','redirect-target','redirect-status','redirect-query','redirect-active','redirect-note','redirect-save'])el(id).disabled=readOnly;el('redirect-delete').hidden=!row||readOnly||!row.id;say('');}
function render(){const q=(filter.value||'').trim().toLowerCase();list.replaceChildren();const visible=rows.filter(row=>!q||row.source.toLowerCase().includes(q)||row.target.toLowerCase().includes(q)||String(row.note||'').toLowerCase().includes(q));if(!visible.length){const p=document.createElement('p');p.className='muted';p.textContent='No redirects match.';list.append(p);return;}for(const row of visible){const b=document.createElement('button');b.type='button';b.className='revision-item';if(selected&&selected.source===row.source)b.setAttribute('aria-current','true');const strong=document.createElement('strong');strong.textContent=row.source;const small=document.createElement('small');small.textContent=`${row.status} → ${row.target}${row.readOnly?' · system':''}${row.active===false?' · inactive':''}`;b.append(strong,small);b.addEventListener('click',()=>{setEditor(row);render();});list.append(b);}}
function apply(data){rows=data.redirects||[];summary.textContent=`${data.summary?.active||0} active · ${data.summary?.editable||0} editable · ${data.summary?.system||0} system`;if(selected){const match=rows.find(row=>row.source===selected.source||row.id&&row.id===selected.id);setEditor(match||null);}render();}
async function load(){apply(await api());}
filter?.addEventListener('input',render);el('redirect-new')?.addEventListener('click',()=>{setEditor(null);render();el('redirect-source').focus();});
form?.addEventListener('submit',async event=>{event.preventDefault();const id=Number(el('redirect-id').value||0);const redirect={id,source:el('redirect-source').value.trim(),target:el('redirect-target').value.trim(),status:Number(el('redirect-status').value),preserveQuery:el('redirect-query').checked,active:el('redirect-active').checked,note:el('redirect-note').value.trim()};say('Saving…');try{const data=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',redirect,expectedHash:selected?.revisionHash||''})});selected=data.saved||null;apply(data);say('Redirect saved and projected.');}catch(e){say(e.message,true);}});
el('redirect-delete')?.addEventListener('click',async()=>{if(!selected?.id||selected.readOnly)return;if(!confirm(`Delete redirect ${selected.source}?`))return;say('Deleting…');try{const data=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id:selected.id,expectedHash:selected.revisionHash,confirm:'DELETE'})});selected=null;apply(data);setEditor(null);say('Redirect deleted and projection refreshed.');}catch(e){say(e.message,true);}});
el('logout')?.addEventListener('click',async()=>{try{await fetch('/api/cms-auth.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CMS-CSRF':csrf},body:JSON.stringify({action:'logout'})});}finally{location.href='/cms/';}});
setEditor(null);load().catch(e=>say(e.message,true));
})();
