<?php
declare(strict_types=1);

/** Friendly CLI initializer for public repository-owned site configuration only. */

function siteSetupUrl(string $raw): string {
    $value=rtrim(trim($raw),'/');$parts=parse_url($value);
    if(!is_array($parts)||isset($parts['user'])||isset($parts['pass'])||isset($parts['query'])||isset($parts['fragment']))throw new RuntimeException('Site URL must be a plain origin without credentials, query, or fragment.');
    $scheme=strtolower((string)($parts['scheme']??''));$host=strtolower((string)($parts['host']??''));
    $local=in_array($host,['localhost','127.0.0.1','::1'],true);
    if($host===''||($scheme!=='https'&&!($scheme==='http'&&$local)))throw new RuntimeException('Use an HTTPS site origin (HTTP is allowed only for localhost development).');
    $path=(string)($parts['path']??'');if($path!==''&&$path!=='/')throw new RuntimeException('Site URL must be an origin without a path.');
    return $value;
}
function siteSetupMark(string $name): string {
    $parts=preg_split('/\s+/u',trim($name))?:[];$mark='';foreach(array_slice($parts,0,2) as $part)$mark.=function_exists('mb_substr')?mb_substr($part,0,1):substr($part,0,1);return strtoupper(substr($mark!==''?$mark:'S',0,8));
}
function siteSetupConfig(array $base,string $name,string $url,string $owner=''): array {
    $name=trim($name);if($name===''||strlen($name)>120)throw new RuntimeException('Site name must be between 1 and 120 characters.');$url=siteSetupUrl($url);$owner=trim($owner);$display=$owner!==''?substr($owner,0,120):$name;
    if(!isset($base['site'])||!is_array($base['site']))$base['site']=[];$base['site']['name']=$name;$base['site']['base_url']=$url;$base['site']['owner_display_name']=$display;
    if(!isset($base['branding'])||!is_array($base['branding']))$base['branding']=[];$base['branding']['mark']=siteSetupMark($name);
    if(isset($base['seo'])&&is_array($base['seo']))$base['seo']['author']=$display;
    return $base;
}
function siteSetupWrite(string $root,array $config,bool $force=false): string {
    $rootReal=realpath($root);if($rootReal===false||!is_dir($rootReal))throw new RuntimeException('Site root is unavailable.');$target=$rootReal.'/config/site.php';$dir=dirname($target);if(!is_dir($dir))throw new RuntimeException('Config directory is unavailable.');if(is_file($target)&&!$force)throw new RuntimeException('config/site.php already exists. Re-run with --force only if replacing repository-owned public configuration is intentional.');
    $php="<?php\ndeclare(strict_types=1);\n\n/** Public site structure generated by setup/site.php. Keep secrets out of this file. */\nreturn ".var_export($config,true).";\n";$tmp=$target.'.tmp-'.bin2hex(random_bytes(4));if(file_put_contents($tmp,$php,LOCK_EX)===false)throw new RuntimeException('Could not write temporary site configuration.');if(!rename($tmp,$target)){@unlink($tmp);throw new RuntimeException('Could not install config/site.php atomically.');}return $target;
}
function siteSetupCli(array $argv): int {
    $options=getopt('',['name:','url:','owner::','force','help']);if(isset($options['help'])){fwrite(STDOUT,"Usage: php setup/site.php --name=\"My Site\" --url=https://example.com [--owner=\"Owner\"] [--force]\nWrites public config/site.php only. It never reads or writes credentials.\n");return 0;}
    $name=(string)($options['name']??'');$url=(string)($options['url']??'');if($name===''||$url===''){fwrite(STDERR,"Both --name and --url are required. Use --help for usage.\n");return 2;}
    $root=dirname(__DIR__);$example=$root.'/config/site.example.php';if(!is_file($example)){fwrite(STDERR,"config/site.example.php is missing.\n");return 2;}
    try{$base=require $example;if(!is_array($base))throw new RuntimeException('Site example configuration is invalid.');$config=siteSetupConfig($base,$name,$url,(string)($options['owner']??''));$target=siteSetupWrite($root,$config,isset($options['force']));fwrite(STDOUT,"Created $target\nNext: configure private AINCMS_* secrets, bootstrap the database, then open /cms/.\n");return 0;}catch(Throwable $e){fwrite(STDERR,$e->getMessage()."\n");return 1;}
}

if(PHP_SAPI==='cli'&&realpath((string)($_SERVER['SCRIPT_FILENAME']??''))===__FILE__)exit(siteSetupCli($argv));
