<?php
declare(strict_types=1);
require_once __DIR__.'/audience.php';
$root=dirname(__DIR__);$method=(string)($_SERVER['REQUEST_METHOD']??'GET');

function audiencePublicPage(string $title,string $message,string $mode='message',string $token=''): never {
    secureCmsHeaders();header('Cross-Origin-Resource-Policy: same-origin');$safeTitle=htmlspecialchars($title,ENT_QUOTES|ENT_HTML5,'UTF-8');$safeMessage=htmlspecialchars($message,ENT_QUOTES|ENT_HTML5,'UTF-8');echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>'.$safeTitle.'</title></head><body><main style="max-width:42rem;margin:10vh auto;padding:1.5rem;font:16px/1.5 system-ui,sans-serif"><h1>'.$safeTitle.'</h1><p>'.$safeMessage.'</p>';
    if($mode==='confirm'&&$token!=='')echo '<form method="post" action="/api/audience-subscribe.php"><input type="hidden" name="confirm_token" value="'.htmlspecialchars($token,ENT_QUOTES|ENT_HTML5,'UTF-8').'"><button type="submit">Confirm subscription</button></form>';else echo '<p><a href="/">Return to site</a></p>';echo '</main></body></html>';exit;
}
if($method==='GET'&&isset($_GET['confirm'])){$token=trim((string)$_GET['confirm']);try{$row=audienceConfirmationRecord($token,false);if(!$row)audiencePublicPage('Confirmation unavailable','That confirmation link is invalid, expired, or already used.');audiencePublicPage('Confirm subscription','Confirm that you want to join '.(string)$row['public_label'].'.','confirm',$token);}catch(Throwable $e){audiencePublicPage('Confirmation unavailable','That confirmation link is unavailable right now.');}}
if($method==='POST'&&isset($_POST['confirm_token'])){requireSameOrigin(true);enforceRateLimit('audience-confirm',20,3600,$root);try{$result=audienceConfirm(trim((string)$_POST['confirm_token']));audiencePublicPage('Subscription confirmed','You are subscribed to '.(string)$result['publicLabel'].'.');}catch(Throwable $e){audiencePublicPage('Confirmation unavailable','That confirmation link is invalid, expired, or already used.');}}
if($method!=='POST'){secureJsonHeaders();runtimeJson(['ok'=>false,'error'=>'Method not allowed.'],405);}requireSameOrigin(true);enforceRateLimit('audience-signup',8,3600,$root);
$contentType=strtolower(trim((string)($_SERVER['CONTENT_TYPE']??'')));$isJson=str_starts_with($contentType,'application/json');$payload=$isJson?readJsonBody(16384):$_POST;$honeypot=trim((string)($payload['company']??''));if($honeypot!==''){if($isJson){secureJsonHeaders();runtimeJson(['ok'=>true,'confirmationRequired'=>true]);}audiencePublicPage('Check your email','If the address can be subscribed, a confirmation message will arrive shortly.');}
try{$result=audienceSubscribe((string)($payload['listKey']??''),(string)($payload['email']??''),'public-form');if($isJson){secureJsonHeaders();runtimeJson(['ok'=>true]+$result);}audiencePublicPage('Check your email','If the address can be subscribed, a confirmation message will arrive shortly.');}
catch(RuntimeException $e){$safe=str_starts_with($e->getMessage(),'Enter a valid email')?$e->getMessage():'The signup could not be completed right now.';if($isJson){secureJsonHeaders();runtimeJson(['ok'=>false,'error'=>$safe],str_starts_with($safe,'Enter')?422:503);}audiencePublicPage('Signup unavailable',$safe);}
catch(Throwable $e){error_log('[audience-signup] '.get_class($e));if($isJson){secureJsonHeaders();runtimeJson(['ok'=>false,'error'=>'The signup could not be completed right now.'],500);}audiencePublicPage('Signup unavailable','The signup could not be completed right now.');}
