<?php
declare(strict_types=1);
require_once __DIR__.'/runtime.php';
require_once __DIR__.'/mail-transport.php';
require_once __DIR__.'/block-presets.php';

/** Canonical Audience list/subscription authority. */
function audienceRequireSchema(): void {dbRequireSchemaVersion(10);}
function audienceSafeKey(string $key): bool {return preg_match('/^[a-z0-9][a-z0-9-]{1,63}$/',$key)===1;}
function audienceNormalizeKey(string $key): string {$key=strtolower(trim($key));if(!audienceSafeKey($key))throw new RuntimeException('Audience list key must use 2–64 lowercase letters, numbers, or hyphens.');return $key;}
function audienceNormalizeEmail(string $email): string {$email=strtolower(trim($email));if($email===''||strlen($email)>254||filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new RuntimeException('Enter a valid email address.');return $email;}
function audienceText(string $value,int $max,string $label,bool $required=true): string {$value=trim($value);if(($required&&$value==='')||strlen($value)>$max)throw new RuntimeException($label.' is invalid.');return $value;}
function audienceListRevision(array $row): string {$data=['key'=>$row['key']??'','label'=>$row['label']??'','publicLabel'=>$row['publicLabel']??'','description'=>$row['description']??'','confirmationSubject'=>$row['confirmationSubject']??'','confirmationBody'=>$row['confirmationBody']??'','status'=>$row['status']??''];$json=json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return hash('sha256',is_string($json)?$json:'');}
function audienceListRow(array $row): array {$out=['key'=>(string)$row['list_key'],'label'=>(string)$row['label'],'publicLabel'=>(string)$row['public_label'],'description'=>(string)$row['description'],'confirmationSubject'=>(string)$row['confirmation_subject'],'confirmationBody'=>(string)$row['confirmation_body'],'status'=>(string)$row['status'],'createdAt'=>dbIso((string)$row['created_at']),'updatedAt'=>dbIso((string)$row['updated_at'])];$out['revisionHash']=audienceListRevision($out);return $out;}
function audienceListRecord(string $key,bool $forUpdate=false): ?array {audienceRequireSchema();$stmt=db()->prepare('SELECT * FROM audience_lists WHERE list_key=?'.($forUpdate?' FOR UPDATE':''));$stmt->execute([audienceNormalizeKey($key)]);$row=$stmt->fetch();return is_array($row)?audienceListRow($row):null;}
function audienceCounts(string $key): array {audienceRequireSchema();$stmt=db()->prepare("SELECT COUNT(*) total,SUM(status='pending') pending,SUM(status='confirmed') confirmed,SUM(status='unsubscribed') unsubscribed FROM audience_subscriptions WHERE list_key=?");$stmt->execute([audienceNormalizeKey($key)]);$row=$stmt->fetch()?:[];return ['total'=>(int)($row['total']??0),'pending'=>(int)($row['pending']??0),'confirmed'=>(int)($row['confirmed']??0),'unsubscribed'=>(int)($row['unsubscribed']??0)];}
function audienceLists(): array {audienceRequireSchema();$out=[];foreach(db()->query('SELECT * FROM audience_lists ORDER BY label,list_key')->fetchAll() as $row){$item=audienceListRow($row);$item['counts']=audienceCounts($item['key']);$out[]=$item;}return $out;}
function audienceSignupPresetKey(string $key): string {return 'audience-signup-'.$key;}
function audienceSignupPresetHtml(array $list): string {
    $key=htmlspecialchars((string)$list['key'],ENT_QUOTES|ENT_HTML5,'UTF-8');$label=htmlspecialchars((string)$list['publicLabel'],ENT_QUOTES|ENT_HTML5,'UTF-8');$description=htmlspecialchars((string)$list['description'],ENT_QUOTES|ENT_HTML5,'UTF-8');$desc=$description!==''?'<p>'.$description.'</p>':'';
    return '<section class="cms-audience-signup" data-audience-list="'.$key.'"><h2>'.$label.'</h2>'.$desc.'<form method="post" action="/api/audience-subscribe.php"><input type="hidden" name="listKey" value="'.$key.'"><label>Email address <input type="email" name="email" autocomplete="email" maxlength="254" required></label><input type="text" name="company" autocomplete="off" tabindex="-1" aria-hidden="true" hidden><button type="submit">Subscribe</button></form><p><small>You will receive an email asking you to confirm.</small></p></section>';
}
function audienceEnsureSignupPreset(array $list): void {
    $key=audienceSignupPresetKey((string)$list['key']);if(!blockPresetSafeKey($key))throw new RuntimeException('Generated Audience signup block key is invalid.');$html=audienceSignupPresetHtml($list);$user=(int)($_SESSION['cms_user_id']??0);$stmt=db()->prepare("INSERT INTO block_presets (preset_key,label,category,preset_kind,html_content,definition_json,variables_json,source_note,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,'legacy',?,'{}','[]',?,NULLIF(?,0),NULLIF(?,0),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE label=VALUES(label),category=VALUES(category),preset_kind='legacy',html_content=VALUES(html_content),definition_json='{}',variables_json='[]',source_note=VALUES(source_note),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()");$stmt->execute([$key,'Signup — '.(string)$list['label'],'Audience',$html,'Generated by Audience list '.(string)$list['key'],$user,$user]);
}
function audienceSaveList(array $input,string $expectedHash=''): array {
    audienceRequireSchema();$key=audienceNormalizeKey((string)($input['key']??''));$label=audienceText((string)($input['label']??''),191,'Audience list label');$public=audienceText((string)($input['publicLabel']??$label),191,'Audience public label');$description=audienceText((string)($input['description']??''),2000,'Audience description',false);$subject=audienceText((string)($input['confirmationSubject']??'Confirm your subscription'),255,'Confirmation subject');$body=audienceText((string)($input['confirmationBody']??'Confirm your subscription by opening {confirmation_url}'),8000,'Confirmation body');if(substr_count($body,'{confirmation_url}')!==1)throw new RuntimeException('Confirmation body must contain exactly one {confirmation_url} placeholder.');$status=(string)($input['status']??'active');if(!in_array($status,['active','disabled'],true))throw new RuntimeException('Audience list status is invalid.');
    $pdo=db();$pdo->beginTransaction();try{$current=audienceListRecord($key,true);if($current&&($expectedHash===''||!hash_equals($expectedHash,(string)$current['revisionHash'])))throw new RuntimeException('Audience list changed since it was opened. Refresh before saving.');$uid=(int)($_SESSION['cms_user_id']??0);if($current){$stmt=$pdo->prepare('UPDATE audience_lists SET label=?,public_label=?,description=?,confirmation_subject=?,confirmation_body=?,status=?,updated_by=NULLIF(?,0),updated_at=UTC_TIMESTAMP() WHERE list_key=?');$stmt->execute([$label,$public,$description,$subject,$body,$status,$uid,$key]);}else{$stmt=$pdo->prepare('INSERT INTO audience_lists (list_key,label,public_label,description,confirmation_subject,confirmation_body,status,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,NULLIF(?,0),NULLIF(?,0),UTC_TIMESTAMP(),UTC_TIMESTAMP())');$stmt->execute([$key,$label,$public,$description,$subject,$body,$status,$uid,$uid]);}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}$saved=audienceListRecord($key);if(!$saved)throw new RuntimeException('Saved Audience list could not be reloaded.');audienceEnsureSignupPreset($saved);return $saved;
}
function audienceSubscriptions(string $key,string $status='all',int $limit=250): array {audienceRequireSchema();$key=audienceNormalizeKey($key);$allowed=['all','pending','confirmed','unsubscribed'];if(!in_array($status,$allowed,true))$status='all';$limit=max(1,min(1000,$limit));$sql='SELECT email,status,requested_at,last_confirmation_sent_at,confirmed_at,unsubscribed_at,source,created_at,updated_at FROM audience_subscriptions WHERE list_key=?'.($status!=='all'?' AND status=?':'').' ORDER BY updated_at DESC,email LIMIT '.$limit;$stmt=db()->prepare($sql);$args=[$key];if($status!=='all')$args[]=$status;$stmt->execute($args);$out=[];foreach($stmt->fetchAll() as $row)$out[]=['email'=>(string)$row['email'],'status'=>(string)$row['status'],'requestedAt'=>dbIso((string)$row['requested_at']),'lastConfirmationSentAt'=>$row['last_confirmation_sent_at']?dbIso((string)$row['last_confirmation_sent_at']):null,'confirmedAt'=>$row['confirmed_at']?dbIso((string)$row['confirmed_at']):null,'unsubscribedAt'=>$row['unsubscribed_at']?dbIso((string)$row['unsubscribed_at']):null,'source'=>(string)$row['source'],'createdAt'=>dbIso((string)$row['created_at']),'updatedAt'=>dbIso((string)$row['updated_at'])];return $out;}
function audienceConfirmationUrl(string $token): string {$origin=rtrim(publicOrigin(),'/');if($origin==='')throw new RuntimeException('Public origin is not configured for confirmation links.');return $origin.'/api/audience-subscribe.php?confirm='.rawurlencode($token);}
function audienceSendConfirmation(array $list,string $email,string $token): void {$url=audienceConfirmationUrl($token);$body=str_replace('{confirmation_url}',$url,(string)$list['confirmationBody']);mailTransportSend($email,(string)$list['confirmationSubject'],$body);}
function audienceSubscribe(string $key,string $email,string $source='public-form'): array {
    audienceRequireSchema();$key=audienceNormalizeKey($key);$email=audienceNormalizeEmail($email);$source=preg_match('/^[a-z0-9-]{2,64}$/',$source)?$source:'public-form';$pdo=db();$list=audienceListRecord($key);if(!$list||$list['status']!=='active')throw new RuntimeException('This signup list is unavailable.');$token='';$send=false;$pdo->beginTransaction();try{$stmt=$pdo->prepare('SELECT * FROM audience_subscriptions WHERE list_key=? AND email=? FOR UPDATE');$stmt->execute([$key,$email]);$row=$stmt->fetch();if(is_array($row)&&$row['status']==='confirmed'){$pdo->commit();return ['accepted'=>true,'confirmationRequired'=>true];}$last=is_array($row)&&$row['last_confirmation_sent_at']?strtotime((string)$row['last_confirmation_sent_at'].' UTC'):0;if($last&&$last>time()-900){$pdo->commit();return ['accepted'=>true,'confirmationRequired'=>true];}$token=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$hash=hash('sha256',$token);if(is_array($row)){$up=$pdo->prepare("UPDATE audience_subscriptions SET status='pending',requested_at=UTC_TIMESTAMP(),last_confirmation_sent_at=UTC_TIMESTAMP(),confirmed_at=NULL,unsubscribed_at=NULL,confirmation_token_hash=?,source=?,updated_at=UTC_TIMESTAMP() WHERE id=?");$up->execute([$hash,$source,(int)$row['id']]);}else{$up=$pdo->prepare("INSERT INTO audience_subscriptions (list_key,email,status,requested_at,last_confirmation_sent_at,confirmation_token_hash,source,created_at,updated_at) VALUES (?,?,'pending',UTC_TIMESTAMP(),UTC_TIMESTAMP(),?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$up->execute([$key,$email,$hash,$source]);}$pdo->commit();$send=true;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    if($send){try{audienceSendConfirmation($list,$email,$token);}catch(Throwable $e){$reset=$pdo->prepare('UPDATE audience_subscriptions SET last_confirmation_sent_at=NULL,updated_at=UTC_TIMESTAMP() WHERE list_key=? AND email=? AND confirmation_token_hash=?');$reset->execute([$key,$email,hash('sha256',$token)]);throw $e;}}return ['accepted'=>true,'confirmationRequired'=>true];
}
function audienceConfirmationRecord(string $token,bool $forUpdate=false): ?array {if(preg_match('/^[A-Za-z0-9_-]{30,120}$/',$token)!==1)return null;audienceRequireSchema();$hash=hash('sha256',$token);$sql="SELECT s.id,s.email,s.status,s.requested_at,s.list_key,l.public_label,l.status list_status FROM audience_subscriptions s JOIN audience_lists l ON l.list_key=s.list_key WHERE s.confirmation_token_hash=? LIMIT 1".($forUpdate?' FOR UPDATE':'');$stmt=db()->prepare($sql);$stmt->execute([$hash]);$row=$stmt->fetch();if(!is_array($row)||$row['status']!=='pending'||$row['list_status']!=='active'||strtotime((string)$row['requested_at'].' UTC')<time()-30*86400)return null;return $row;}
function audienceConfirm(string $token): array {$pdo=db();$pdo->beginTransaction();try{$row=audienceConfirmationRecord($token,true);if(!$row)throw new RuntimeException('That confirmation link is unavailable or expired.');$up=$pdo->prepare("UPDATE audience_subscriptions SET status='confirmed',confirmed_at=UTC_TIMESTAMP(),unsubscribed_at=NULL,confirmation_token_hash=NULL,last_confirmation_sent_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=? AND status='pending'");$up->execute([(int)$row['id']]);if($up->rowCount()!==1)throw new RuntimeException('That confirmation link is unavailable or expired.');$pdo->commit();return ['listKey'=>(string)$row['list_key'],'publicLabel'=>(string)$row['public_label']];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
function audienceUnsubscribeOperator(string $key,string $email): void {audienceRequireSchema();$key=audienceNormalizeKey($key);$email=audienceNormalizeEmail($email);$stmt=db()->prepare("UPDATE audience_subscriptions SET status='unsubscribed',unsubscribed_at=UTC_TIMESTAMP(),confirmation_token_hash=NULL,last_confirmation_sent_at=NULL,updated_at=UTC_TIMESTAMP() WHERE list_key=? AND email=?");$stmt->execute([$key,$email]);if($stmt->rowCount()===0)throw new RuntimeException('Audience member was not found.');}
function audienceResendOperator(string $key,string $email): void {$key=audienceNormalizeKey($key);$email=audienceNormalizeEmail($email);$stmt=db()->prepare("SELECT last_confirmation_sent_at FROM audience_subscriptions WHERE list_key=? AND email=? AND status='pending'");$stmt->execute([$key,$email]);$row=$stmt->fetch();if(!is_array($row))throw new RuntimeException('Only pending subscriptions can be resent.');$last=$row['last_confirmation_sent_at']?strtotime((string)$row['last_confirmation_sent_at'].' UTC'):0;if($last&&$last>time()-900)throw new RuntimeException('Confirmation was sent recently. Try again after the resend cooldown.');audienceSubscribe($key,$email,'operator-resend');}
