<?php
declare(strict_types=1);
require_once __DIR__.'/composer.php';
require_once __DIR__.'/composer-primitives.php';

/** Schema-v9 reusable block authority with a read-only schema-v8 compatibility seam for safe upgrades. */
function blockPresetSafeKey(string $key): bool {return preg_match('/^[a-z0-9][a-z0-9-]{2,190}$/',$key)===1;}
function blockPresetKey(string $label): string {$slug=strtolower(trim(preg_replace('/[^A-Za-z0-9]+/','-',$label)??'','-'))?:'block';return substr($slug,0,150).'-'.substr(hash('sha256',$label.'|'.microtime(true).'|'.random_int(1,PHP_INT_MAX)),0,12);}
function blockPresetSchemaVersion(): int {try{return (int)db()->query('SELECT schema_version FROM app_meta WHERE id=1')->fetchColumn();}catch(Throwable $e){return 0;}}
function blockPresetLegacyRecord(string $key): ?array {
    try{$stmt=db()->prepare('SELECT template_key,label,category,source_page,source_ordinal,html_content,variables_json,created_at,updated_at FROM page_block_templates WHERE template_key=?');$stmt->execute([$key]);$row=$stmt->fetch();}catch(Throwable $e){return null;}if(!is_array($row))return null;
    $variables=dbJsonDecode((string)$row['variables_json']);if(!$variables)$variables=composerTemplateVariables((string)$row['html_content']);$ordinal=(int)$row['source_ordinal']+1;$source=trim((string)$row['source_page']);
    return ['key'=>(string)$row['template_key'],'label'=>(string)$row['label'],'category'=>(string)$row['category'],'kind'=>'legacy','html'=>(string)$row['html_content'],'definition'=>[],'variables'=>$variables,'defaults'=>composerTemplateDefaults($variables),'sourceNote'=>$source!==''?'Repository structure: '.$source.' #'.$ordinal:'Repository structure','createdAt'=>dbIso((string)$row['created_at']),'updatedAt'=>dbIso((string)$row['updated_at'])];
}
function blockPresetRecord(string $key): ?array {
    if(blockPresetSchemaVersion()<9)return blockPresetLegacyRecord($key);
    $stmt=db()->prepare('SELECT preset_key,label,category,preset_kind,html_content,definition_json,variables_json,source_note,created_at,updated_at FROM block_presets WHERE preset_key=?');$stmt->execute([$key]);$row=$stmt->fetch();if(!is_array($row))return null;
    $definition=dbJsonDecode((string)$row['definition_json']);$variables=dbJsonDecode((string)$row['variables_json']);$kind=(string)$row['preset_kind'];if($kind==='primitive')$variables=composerPrimitiveVariables($definition);elseif(!$variables)$variables=composerTemplateVariables((string)$row['html_content']);
    return ['key'=>(string)$row['preset_key'],'label'=>(string)$row['label'],'category'=>(string)$row['category'],'kind'=>$kind,'html'=>(string)$row['html_content'],'definition'=>$definition,'variables'=>$variables,'defaults'=>composerTemplateDefaults($variables),'sourceNote'=>(string)$row['source_note'],'createdAt'=>dbIso((string)$row['created_at']),'updatedAt'=>dbIso((string)$row['updated_at'])];
}
function blockPresetUsageCount(string $key): int {$count=0;foreach(db()->query('SELECT blocks_json FROM page_compositions')->fetchAll() as $row){foreach(dbJsonDecode((string)$row['blocks_json']) as $block)if(is_array($block)&&(($block['presetKey']??$block['templateKey']??null)===$key))$count++;}return $count;}
function blockPresets(): array {
    $schema=blockPresetSchemaVersion();$rows=$schema>=9?db()->query('SELECT preset_key AS item_key FROM block_presets ORDER BY category,label,preset_key')->fetchAll():db()->query('SELECT template_key AS item_key FROM page_block_templates ORDER BY category,label,template_key')->fetchAll();$out=[];
    foreach($rows as $row){$record=blockPresetRecord((string)$row['item_key']);if(!$record)continue;$preview=$record['kind']==='primitive'?implode(' · ',array_map(fn($e)=>ucfirst((string)($e['type']??'element')),(array)($record['definition']['elements']??[]))):composerSubstr(composerText((string)$record['html']),180);$record['preview']=$preview;$record['usage']=blockPresetUsageCount((string)$record['key']);unset($record['html']);$out[]=$record;}return $out;
}
function blockPresetRender(string $root,string $key,array $input,string $instanceId): array {
    $record=blockPresetRecord($key);if(!$record)throw new RuntimeException('A referenced block preset is unavailable: '.$key);
    if($record['kind']==='primitive'){$applied=composerPrimitiveApplyValues($root,(array)$record['definition'],(array)$record['variables'],$input);$rendered=composerPrimitiveRender($root,(array)$applied['definition'],$instanceId);return ['presetKey'=>$key,'instanceId'=>$instanceId,'values'=>$applied['values'],'html'=>$rendered['html'],'record'=>$record];}
    $values=composerNormalizeValues($root,(array)$record['variables'],$input);$html=composerApplyValues($root,(string)$record['html'],(array)$record['variables'],$values);$html=composerRekeyEditableIds($html,$instanceId);$html=composerAnnotateBlock($html,$instanceId);return ['presetKey'=>$key,'instanceId'=>$instanceId,'values'=>$values,'html'=>$html,'record'=>$record];
}
function blockPresetSavePrimitive(string $root,?string $key,string $label,string $category,array $definition): array {
    dbRequireSchemaVersion(9);$label=composerPrimitiveSubstr(trim($label),191);if($label==='')throw new RuntimeException('Block name is required.');$category=composerPrimitiveSubstr(trim($category),96)?:'Designed';$key=$key!==null&&$key!==''?$key:blockPresetKey($label);if(!blockPresetSafeKey($key))throw new RuntimeException('Invalid block preset identifier.');$existing=blockPresetRecord($key);if($existing&&$existing['kind']!=='primitive')throw new RuntimeException('Converted presets preserve governed structure and cannot be replaced with a primitive definition.');
    $definition['label']=$label;$normalized=composerPrimitiveNormalize($root,$definition,'preset-edit-01');$variables=composerPrimitiveVariables($normalized);$user=(int)($_SESSION['cms_user_id']??0);$stmt=db()->prepare("INSERT INTO block_presets (preset_key,label,category,preset_kind,html_content,definition_json,variables_json,source_note,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,'primitive','',?,?,?,NULLIF(?,0),NULLIF(?,0),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE label=VALUES(label),category=VALUES(category),preset_kind='primitive',html_content='',definition_json=VALUES(definition_json),variables_json=VALUES(variables_json),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()");$stmt->execute([$key,$label,$category,dbJsonEncode($normalized),dbJsonEncode($variables),'Designed in Block Composer',$user,$user]);return blockPresetRecord($key)??[];
}
/** Save a selected typed instance as a new preset without mutating its source preset or page placement. */
function blockPresetSaveAsNew(string $root,string $sourceKey,string $instanceId,array $values,string $label,string $category): array {
    dbRequireSchemaVersion(9);if(!composerSafeInstanceId($instanceId))throw new RuntimeException('Invalid page block instance identifier.');$source=blockPresetRecord($sourceKey);if(!$source)throw new RuntimeException('The source block preset is unavailable. Refresh Page Composer and try again.');
    $label=composerPrimitiveSubstr(trim($label),191);if($label==='')throw new RuntimeException('Block name is required.');$category=composerPrimitiveSubstr(trim($category),96)?:'Section';
    if(($source['kind']??'legacy')==='primitive'){$applied=composerPrimitiveApplyValues($root,(array)$source['definition'],(array)$source['variables'],$values);$definition=(array)$applied['definition'];$definition['label']=$label;return blockPresetSavePrimitive($root,null,$label,$category,$definition);}
    $normalized=composerNormalizeValues($root,(array)$source['variables'],$values);$html=composerApplyValues($root,(string)$source['html'],(array)$source['variables'],$normalized);$variables=composerTemplateVariables($html);$key=blockPresetKey($label);$user=(int)($_SESSION['cms_user_id']??0);$stmt=db()->prepare("INSERT INTO block_presets (preset_key,label,category,preset_kind,html_content,definition_json,variables_json,source_note,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,'legacy',?,'{}',?,?,NULLIF(?,0),NULLIF(?,0),UTC_TIMESTAMP(),UTC_TIMESTAMP())");$stmt->execute([$key,$label,$category,$html,dbJsonEncode($variables),'Saved as new from preset '.$sourceKey.' instance '.$instanceId,$user,$user]);$saved=blockPresetRecord($key);if(!$saved)throw new RuntimeException('Saved block preset could not be reloaded.');return $saved;
}
function blockPresetUpdateMetadata(string $key,string $label,string $category): array {dbRequireSchemaVersion(9);if(!blockPresetSafeKey($key)||!blockPresetRecord($key))throw new RuntimeException('Block preset not found.');$label=composerPrimitiveSubstr(trim($label),191);if($label==='')throw new RuntimeException('Block name is required.');$category=composerPrimitiveSubstr(trim($category),96)?:'Section';$user=(int)($_SESSION['cms_user_id']??0);$stmt=db()->prepare('UPDATE block_presets SET label=?,category=?,updated_by=NULLIF(?,0),updated_at=UTC_TIMESTAMP() WHERE preset_key=?');$stmt->execute([$label,$category,$user,$key]);return blockPresetRecord($key)??[];}
function blockPresetDelete(string $key): void {dbRequireSchemaVersion(9);if(blockPresetUsageCount($key)>0)throw new RuntimeException('This block preset is already used by a page. Remove those instances before deleting it.');$stmt=db()->prepare('DELETE FROM block_presets WHERE preset_key=?');$stmt->execute([$key]);if($stmt->rowCount()===0)throw new RuntimeException('Block preset not found.');}
function blockPresetBootstrap(string $root): array {
    dbRequireSchemaVersion(9);$pdo=db();$existing=(int)$pdo->query('SELECT COUNT(*) FROM block_presets')->fetchColumn();
    $insert=$pdo->prepare("INSERT IGNORE INTO block_presets (preset_key,label,category,preset_kind,html_content,definition_json,variables_json,source_note,created_at,updated_at) VALUES (?,?,?,'legacy',?,'{}',?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$created=0;
    foreach(cmsConfiguredPages($root) as $path=>$label){$html=composerSourceHtml($root,$path);foreach(composerExtractTopBlocks($html) as $i=>$block){$key=composerTemplateKey($path,$i);$vars=composerTemplateVariables($block);$insert->execute([$key,composerTemplateLabel($block,$i),composerTemplateCategory($block),$block,dbJsonEncode($vars),'Converted from repository page structure']);$created+=$insert->rowCount();}}
    return ['created'=>$created,'existing'=>$existing,'total'=>$existing+$created];
}
