<?php
declare(strict_types=1);
require_once __DIR__.'/audience.php';
secureJsonHeaders();requireCmsAuth(true);$root=dirname(__DIR__);$method=(string)($_SERVER['REQUEST_METHOD']??'GET');
function cmsAudiencePayload(string $selected=''): array {$lists=audienceLists();$key=$selected;if($key===''&&$lists)$key=(string)$lists[0]['key'];$members=$key!==''?audienceSubscriptions($key,'all',500):[];return ['ok'=>true,'lists'=>$lists,'selectedKey'=>$key,'members'=>$members,'mail'=>mailTransportStatus()];}
function cmsAudienceSafeError(Throwable $e): ?string {if(!$e instanceof RuntimeException)return null;$m=$e->getMessage();foreach(['Audience ','Confirmation ','Enter a valid email','Only pending ','Outgoing mail ','Mail ','SMTP ','Unencrypted ','This signup ','Public origin ','Generated Audience ','Saved Audience '] as $prefix)if(str_starts_with($m,$prefix))return $m;return null;}
try{
    audienceRequireSchema();if($method==='GET')runtimeJson(cmsAudiencePayload(trim((string)($_GET['list']??''))));if($method!=='POST')runtimeJson(['ok'=>false,'error'=>'Method not allowed.'],405);requireSameOrigin(true);requireCmsCsrf();enforceRateLimit('cms-audience',100,3600,$root);$payload=readJsonBody(65536);$action=(string)($payload['action']??'');$key=trim((string)($payload['listKey']??''));
    if($action==='saveList'){if(!is_array($payload['list']??null))runtimeJson(['ok'=>false,'error'=>'Audience list payload is required.'],422);$expected=trim((string)($payload['expectedHash']??''));$candidate=$payload['list'];$existing=audienceListRecord((string)($candidate['key']??''));if($existing&&$expected==='')runtimeJson(['ok'=>false,'error'=>'Expected Audience list revision is required.'],422);$saved=audienceSaveList($candidate,$expected);cmsAudit('audience','Saved Audience list',['listKey'=>$saved['key'],'status'=>$saved['status']],$root);runtimeJson(cmsAudiencePayload($saved['key'])+['saved'=>$saved]);}
    if($action==='unsubscribe'){audienceUnsubscribeOperator($key,(string)($payload['email']??''));cmsAudit('audience','Unsubscribed Audience member',['listKey'=>$key],$root);runtimeJson(cmsAudiencePayload($key));}
    if($action==='resend'){audienceResendOperator($key,(string)($payload['email']??''));cmsAudit('audience','Resent Audience confirmation',['listKey'=>$key],$root);runtimeJson(cmsAudiencePayload($key));}
    if($action==='testMail'){$recipient=audienceNormalizeEmail((string)($payload['email']??''));mailTransportSend($recipient,'AI Native CMS email test','This is a transactional email-delivery test from AI Native CMS.');cmsAudit('audience','Sent outgoing mail transport test',['transport'=>(string)(mailTransportStatus()['transport']??'unknown')],$root);runtimeJson(cmsAudiencePayload($key)+['testSent'=>true]);}
    runtimeJson(['ok'=>false,'error'=>'Unknown Audience action.'],422);
}catch(Throwable $e){if($e instanceof RuntimeException&&str_contains($e->getMessage(),'schema upgrade required'))runtimeJson(['ok'=>false,'error'=>'Audience management requires schema v10. Run the explicit 9-to-10 migration from CLI.','migrationRequired'=>true],409);$safe=cmsAudienceSafeError($e);if($safe!==null)runtimeJson(['ok'=>false,'error'=>$safe],str_contains($safe,'changed since')?409:422);runtimeError($e,'The Audience operation could not be completed.',500);}
