<?php
declare(strict_types=1);
require_once __DIR__.'/block-presets.php';
require_once __DIR__.'/content-authority.php';

/** Canonical page composition, dynamic-page identity, parent hierarchy, and preset-instance snapshots. */
function compositionHashValue(?array $record): string {if($record===null)return 'none';$payload=['path'=>$record['path'],'label'=>$record['label'],'title'=>$record['title'],'shellPath'=>$record['shellPath'],'parentPath'=>$record['parentPath'],'blocks'=>$record['blocks']];$json=json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION);if(!is_string($json))throw new RuntimeException('Could not encode page composition.');return hash('sha256',$json);}
function compositionRecord(string $path): ?array {$stmt=db()->prepare('SELECT page_path,label,title,shell_path,parent_path,blocks_json,updated_at FROM page_compositions WHERE page_path=?');$stmt->execute([$path]);$row=$stmt->fetch();if(!is_array($row))return null;$record=['path'=>(string)$row['page_path'],'label'=>(string)$row['label'],'title'=>(string)$row['title'],'shellPath'=>(string)$row['shell_path'],'parentPath'=>$row['parent_path']!==null?(string)$row['parent_path']:null,'blocks'=>dbJsonDecode((string)$row['blocks_json']),'updatedAt'=>dbIso((string)$row['updated_at'])];$record['hash']=compositionHashValue($record);return $record;}
function compositionExists(string $path): bool {return compositionRecord($path)!==null;}
function compositionList(): array {$rows=db()->query('SELECT page_path FROM page_compositions ORDER BY page_path')->fetchAll();$out=[];foreach($rows as $row){$r=compositionRecord((string)$row['page_path']);if($r)$out[]=$r;}return $out;}
function compositionParentMap(): array {$out=[];foreach(compositionList() as $r)$out[(string)$r['path']]=$r['parentPath'];return $out;}
function compositionValidateParent(string $root,string $path,?string $parentPath): ?string {$parentPath=$parentPath!==null?trim($parentPath):null;if($parentPath==='')$parentPath=null;if($parentPath===null)return null;$managed=cmsManagedPages($root);if(!isset($managed[$parentPath])||$parentPath===$path)throw new RuntimeException('Choose a valid parent page or Site root.');$parents=compositionParentMap();$seen=[$path=>true];$cursor=$parentPath;while($cursor!==null&&$cursor!==''){if(isset($seen[$cursor]))throw new RuntimeException('Page hierarchy cannot contain a parent cycle.');$seen[$cursor]=true;$next=$parents[$cursor]??null;$cursor=is_string($next)&&$next!==''?$next:null;}return $parentPath;}
function compositionSafeNewPagePath(string $path): bool {return preg_match('/^[a-z0-9](?:[a-z0-9-]{0,78}[a-z0-9])?\.html$/',$path)===1&&$path!=='index.html';}
function compositionRenderBlock(string $root,array $item): array {$key=trim((string)($item['presetKey']??''));$instance=trim((string)($item['instanceId']??''));if($key===''||!composerSafeInstanceId($instance))throw new RuntimeException('Invalid composition block identity.');return blockPresetRender($root,$key,is_array($item['values']??null)?$item['values']:[],$instance);}
function compositionShellHtml(string $root,string $path,?string $shellPath=null): string {$source=$shellPath!==null&&$shellPath!==''?$shellPath:$path;$doc=contentAuthorityReadDocument(contentAuthorityPageSourceKey($source));if($doc)return (string)$doc['content'];$full=cmsSafePublicFile($root,$source);if($full===null)throw new RuntimeException('Page shell is unavailable.');return (string)file_get_contents($full);}
function compositionTargetCanonical(string $path): string {$base=rtrim((string)siteConfigValue('site','base_url',''),'/');return $path==='index.html'?$base.'/':$base.'/'.ltrim($path,'/');}
function compositionRetargetShell(string $html,string $path,string $title): string {$title=trim($title);if($title!==''){$safe=htmlspecialchars($title,ENT_QUOTES|ENT_HTML5,'UTF-8');$html=preg_match('/<title>.*?<\/title>/is',$html)?(preg_replace('/<title>.*?<\/title>/is','<title>'.$safe.'</title>',$html,1)??$html):$html;}$canonical=compositionTargetCanonical($path);$html=preg_replace_callback('/<link\b(?=[^>]*\brel=["\']canonical["\'])[^>]*>/is',fn($m)=>composerSetTagAttribute($m[0],'href',$canonical),$html,1)??$html;$html=preg_replace_callback('/<meta\b(?=[^>]*\bproperty=["\']og:url["\'])[^>]*>/is',fn($m)=>composerSetTagAttribute($m[0],'content',$canonical),$html,1)??$html;return $html;}
function compositionStructuralHtml(string $root,string $path,array $blocks,?string $shellPath=null,string $title=''): string {$rendered=[];$seen=[];if(!$blocks||count($blocks)>80)throw new RuntimeException('A composition needs between 1 and 80 blocks.');foreach($blocks as $item){if(!is_array($item))throw new RuntimeException('Invalid composition block.');$row=compositionRenderBlock($root,$item);if(isset($seen[$row['instanceId']]))throw new RuntimeException('Duplicate composition block identity.');$seen[$row['instanceId']]=true;$rendered[]=$row['html'];}$html=composerReplaceMain(compositionShellHtml($root,$path,$shellPath),$rendered);if($shellPath!==null&&$shellPath!==''&&$shellPath!==$path)$html=compositionRetargetShell($html,$path,$title);$h1=preg_match_all('/<h1\b/i',$html,$m);if($h1!==1)throw new RuntimeException('A composed public page must contain exactly one H1 heading.');return $html;}
function compositionSyncCanonicalBlocks(string $path,string $structural): int {$next=cmsExtractEditableBlocks($structural);$current=contentAuthorityPageBlocks($path);$pdo=db();$user=(int)($_SESSION['cms_user_id']??0);$pdo->prepare('DELETE FROM page_blocks WHERE page_path=?')->execute([$path]);$insert=$pdo->prepare('INSERT INTO page_blocks (page_path,block_id,tag_name,html_content,content_sha256,source_sha256,source_ref,source_updated_at,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,UTC_TIMESTAMP(),NULLIF(?,0),UTC_TIMESTAMP())');foreach($next as $block){$id=(string)$block['id'];$html=isset($current[$id])?(string)$current[$id]['html']:(string)$block['html'];$insert->execute([$path,$id,$block['tag'],$html,hash('sha256',$html),(string)$block['hash'],'composition',$user]);}return count($next);}
function compositionProjectPage(string $root,string $path): array {$record=compositionRecord($path);if(!$record)throw new RuntimeException('Page has no canonical composition.');$structural=compositionStructuralHtml($root,$path,(array)$record['blocks'],(string)$record['shellPath'],(string)$record['title']);$leaves=compositionSyncCanonicalBlocks($path,$structural);$html=contentAuthorityOverlayBlocks($structural,$path);$target=cmsSafePublicFile($root,$path)??cmsSafePublicTarget($root,$path);if($target===null)throw new RuntimeException('Composed page target is unavailable.');cmsAtomicWrite($target,$html);return ['path'=>$path,'hash'=>hash('sha256',$html),'blocks'=>count((array)$record['blocks']),'editableBlocks'=>$leaves];}
function compositionProjectAll(string $root): array {$items=[];foreach(compositionList() as $record)$items[]=compositionProjectPage($root,(string)$record['path']);return ['pages'=>count($items),'items'=>$items];}
function projectCmsPage(string $root,string $path): void {if(compositionExists($path))compositionProjectPage($root,$path);else contentAuthorityProjectPage($root,$path);}
function compositionNormalizeItems(string $root,array $items): array {$normalized=[];$seen=[];foreach($items as $item){if(!is_array($item))throw new RuntimeException('Invalid composition block.');$rendered=compositionRenderBlock($root,$item);if(isset($seen[$rendered['instanceId']]))throw new RuntimeException('Duplicate composition block identity.');$seen[$rendered['instanceId']]=true;$normalized[]=['presetKey'=>$rendered['presetKey'],'instanceId'=>$rendered['instanceId'],'values'=>$rendered['values']];}return $normalized;}
function compositionSave(string $root,string $path,array $items,string $expectedHash,?array $metadata=null): array {$pages=cmsManagedPages($root);if(!isset($pages[$path]))throw new RuntimeException('Page is not CMS-managed.');$current=compositionRecord($path);$actual=compositionHashValue($current);if($expectedHash===''||!hash_equals($actual,$expectedHash))throw new RuntimeException('Page composition changed since it was opened. Refresh before saving.');$metadata=is_array($metadata)?$metadata:[];$label=trim((string)($metadata['label']??$current['label']??$pages[$path]));$title=trim((string)($metadata['title']??$current['title']??''));$shell=trim((string)($metadata['shellPath']??$current['shellPath']??$path));$parent=compositionValidateParent($root,$path,array_key_exists('parentPath',$metadata)?($metadata['parentPath']!==null?(string)$metadata['parentPath']:null):($current['parentPath']??null));if($label===''||strlen($label)>191||strlen($title)>512||!isset($pages[$shell]))throw new RuntimeException('Composition page metadata is invalid.');$normalized=compositionNormalizeItems($root,$items);$structural=compositionStructuralHtml($root,$path,$normalized,$shell,$title);$target=cmsSafePublicFile($root,$path);if($target===null)throw new RuntimeException('Managed page target is unavailable.');$before=(string)file_get_contents($target);$user=(int)($_SESSION['cms_user_id']??0);$pdo=db();$pdo->beginTransaction();$wrote=false;try{contentAuthorityBackupPage($path,$before,'composition');$stmt=$pdo->prepare('INSERT INTO page_compositions (page_path,label,title,shell_path,parent_path,blocks_json,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,NULLIF(?,0),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE label=VALUES(label),title=VALUES(title),shell_path=VALUES(shell_path),parent_path=VALUES(parent_path),blocks_json=VALUES(blocks_json),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()');$stmt->execute([$path,$label,$title,$shell,$parent,dbJsonEncode($normalized),$user]);$leaves=compositionSyncCanonicalBlocks($path,$structural);$html=contentAuthorityOverlayBlocks($structural,$path);cmsAtomicWrite($target,$html);$wrote=true;$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($wrote)try{cmsAtomicWrite($target,$before);}catch(Throwable $ignored){}throw $e;}$saved=compositionRecord($path);if(!$saved)throw new RuntimeException('Saved composition could not be reloaded.');cmsAudit('composer','Saved preset-based page composition',['page'=>$path,'blocks'=>count($normalized),'editableBlocks'=>$leaves,'parentPath'=>$parent],$root);return $saved;}
function compositionCreatePage(string $root,string $path,string $label,string $title,string $shellPath,?string $parentPath,array $items): array {$path=trim($path);$label=trim($label);$title=trim($title);$shellPath=trim($shellPath);if(!compositionSafeNewPagePath($path))throw new RuntimeException('New page path must be a lowercase root-level .html filename.');if(isset(cmsManagedPages($root)[$path])||is_file(rtrim($root,'/\\').'/'.$path))throw new RuntimeException('That page path already exists.');$shells=cmsManagedPages($root);if(!isset($shells[$shellPath])||cmsSafePublicFile($root,$shellPath)===null)throw new RuntimeException('Choose a valid existing page shell.');if($label===''||strlen($label)>191||$title===''||strlen($title)>512)throw new RuntimeException('New page label and title are required.');$parent=compositionValidateParent($root,$path,$parentPath);$normalized=compositionNormalizeItems($root,$items);$structural=compositionStructuralHtml($root,$path,$normalized,$shellPath,$title);$target=cmsSafePublicTarget($root,$path);if($target===null)throw new RuntimeException('New page target is unavailable.');$user=(int)($_SESSION['cms_user_id']??0);$pdo=db();$pdo->beginTransaction();$wrote=false;try{$stmt=$pdo->prepare('INSERT INTO page_compositions (page_path,label,title,shell_path,parent_path,blocks_json,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,NULLIF(?,0),UTC_TIMESTAMP(),UTC_TIMESTAMP())');$stmt->execute([$path,$label,$title,$shellPath,$parent,dbJsonEncode($normalized),$user]);$leaves=compositionSyncCanonicalBlocks($path,$structural);$html=contentAuthorityOverlayBlocks($structural,$path);cmsAtomicWrite($target,$html);$wrote=true;$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($wrote&&is_file($target))@unlink($target);throw $e;}$saved=compositionRecord($path);if(!$saved)throw new RuntimeException('Created page could not be reloaded.');cmsAudit('composer','Created canonical composed page',['page'=>$path,'shellPath'=>$shellPath,'parentPath'=>$parent,'blocks'=>count($normalized),'editableBlocks'=>$leaves],$root);return $saved;}
function compositionInitialItems(string $root,string $path): array {$record=compositionRecord($path);return $record?(array)$record['blocks']:[];}
function compositionPayload(string $root,string $path): array {$managed=cmsManagedPages($root);if(!isset($managed[$path]))throw new RuntimeException('Page is not CMS-managed.');$record=compositionRecord($path);$items=compositionInitialItems($root,$path);$blocks=[];foreach($items as $item){$preset=blockPresetRecord((string)($item['presetKey']??''));if(!$preset)continue;$blocks[]=['presetKey'=>$item['presetKey'],'instanceId'=>$item['instanceId'],'values'=>$item['values'],'label'=>$preset['label'],'category'=>$preset['category'],'variables'=>$preset['variables']];}return ['path'=>$path,'label'=>$record['label']??$managed[$path],'title'=>$record['title']??'','shellPath'=>$record['shellPath']??$path,'parentPath'=>$record['parentPath']??null,'composed'=>$record!==null,'hash'=>$record['hash']??'none','blocks'=>$blocks];}
