<?php
declare(strict_types=1);

/** Compare-and-swap release updates for canonical SEO state. Existing CMS authorship wins by default. */
function contentSyncSeoState(array $value): array {
    return [
        'title'=>(string)($value['title']??''),'description'=>(string)($value['description']??''),'canonical'=>(string)($value['canonical']??''),'robots'=>(string)($value['robots']??''),
        'ogTitle'=>(string)($value['ogTitle']??$value['og_title']??''),'ogDescription'=>(string)($value['ogDescription']??$value['og_description']??''),'twitterTitle'=>(string)($value['twitterTitle']??$value['twitter_title']??''),'twitterDescription'=>(string)($value['twitterDescription']??$value['twitter_description']??''),
        'indexable'=>(int)($value['indexable']??1),'followLinks'=>(int)($value['followLinks']??$value['follow_links']??1),'archiveAllowed'=>(int)($value['archiveAllowed']??$value['archive_allowed']??1),'snippetLimit'=>(int)($value['snippetLimit']??$value['snippet_limit']??-1),
        'imagePreview'=>(string)($value['imagePreview']??$value['image_preview']??'large'),'videoPreviewLimit'=>(int)($value['videoPreviewLimit']??$value['video_preview_limit']??-1),'canonicalMode'=>(string)($value['canonicalMode']??$value['canonical_mode']??'self'),'socialMode'=>(string)($value['socialMode']??$value['social_mode']??'inherit'),
    ];
}
function contentSyncSeoHash(array $state): string {$json=json_encode($state,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if(!is_string($json))throw new RuntimeException('Could not encode SEO update state.');return hash('sha256',$json);}
function contentSyncApplySeoOverride(PDO $pdo,array $change,string $origin,string $originRef): string {
    $page=trim((string)($change['page']??''));$seo=(array)($change['seo']??[]);if($page===''||!str_ends_with($page,'.html'))throw new RuntimeException('Invalid SEO update target.');
    $title=trim((string)($seo['title']??''));$description=trim((string)($seo['description']??''));$canonical=trim((string)($seo['canonical']??''));if($title===''||$description===''||$canonical==='')throw new RuntimeException('SEO update requires title, description, and canonical.');if(!seoCanonicalAllowed($canonical))throw new RuntimeException('SEO update canonical must stay on the configured public origin.');
    $seo['robots']=trim((string)($seo['robots']??'index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1'));$seo['ogTitle']=(string)($seo['ogTitle']??$title);$seo['ogDescription']=(string)($seo['ogDescription']??$description);$seo['twitterTitle']=(string)($seo['twitterTitle']??$title);$seo['twitterDescription']=(string)($seo['twitterDescription']??$description);$seo['canonicalMode']=(string)($seo['canonicalMode']??'self');$seo['socialMode']=(string)($seo['socialMode']??'inherit');$next=contentSyncSeoState($seo);$after=contentSyncSeoHash($next);
    $select=$pdo->prepare('SELECT page_path,title,description,canonical,robots,og_title,og_description,twitter_title,twitter_description,indexable,follow_links,archive_allowed,snippet_limit,image_preview,video_preview_limit,canonical_mode,social_mode FROM seo_overrides WHERE page_path=? FOR UPDATE');$select->execute([$page]);$row=$select->fetch();
    if(!$row){$insert=$pdo->prepare('INSERT INTO seo_overrides (page_path,title,description,canonical,robots,og_title,og_description,twitter_title,twitter_description,indexable,follow_links,archive_allowed,snippet_limit,image_preview,video_preview_limit,canonical_mode,social_mode,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP())');$insert->execute([$page,$next['title'],$next['description'],$next['canonical'],$next['robots'],$next['ogTitle'],$next['ogDescription'],$next['twitterTitle'],$next['twitterDescription'],$next['indexable'],$next['followLinks'],$next['archiveAllowed'],$next['snippetLimit'],$next['imagePreview'],$next['videoPreviewLimit'],$next['canonicalMode'],$next['socialMode']]);contentAuthorityLogChange($pdo,'seo_override',$page,$origin,$originRef,'applied','',$after,$after,'Release SEO override entered canonical SQL without changing page/post copy.');return 'applied';}
    $current=contentSyncSeoState($row);$before=contentSyncSeoHash($current);if(hash_equals($before,$after)){contentAuthorityLogChange($pdo,'seo_override',$page,$origin,$originRef,'already_current',$before,$before,$after,'SEO override already matches the release state.');return 'already_current';}
    $expected=trim((string)($change['expectedHash']??''));if($expected===''||!hash_equals($expected,$before)){contentAuthorityLogChange($pdo,'seo_override',$page,$origin,$originRef,'preserved_newer',$before,$before,$after,'Existing canonical SEO override was preserved instead of being replaced by release metadata.');return 'preserved_newer';}
    $update=$pdo->prepare('UPDATE seo_overrides SET title=?,description=?,canonical=?,robots=?,og_title=?,og_description=?,twitter_title=?,twitter_description=?,indexable=?,follow_links=?,archive_allowed=?,snippet_limit=?,image_preview=?,video_preview_limit=?,canonical_mode=?,social_mode=?,updated_at=UTC_TIMESTAMP() WHERE page_path=?');$update->execute([$next['title'],$next['description'],$next['canonical'],$next['robots'],$next['ogTitle'],$next['ogDescription'],$next['twitterTitle'],$next['twitterDescription'],$next['indexable'],$next['followLinks'],$next['archiveAllowed'],$next['snippetLimit'],$next['imagePreview'],$next['videoPreviewLimit'],$next['canonicalMode'],$next['socialMode'],$page]);contentAuthorityLogChange($pdo,'seo_override',$page,$origin,$originRef,'applied',$before,$after,$after,'SEO override advanced from the explicitly expected predecessor.');return 'applied';
}
