<?php
declare(strict_types=1);
require_once __DIR__.'/seo.php';
require_once __DIR__.'/presentation-core.php';

/** Read-only site-wide SEO QA. Findings never become a second authored-state authority. */

function seoQualityIssue(string $code,string $severity,string $message,?string $path=null,array $context=[]): array {return compact('code','severity','message','path','context');}
function seoQualityFold(string $value): string {return function_exists('mb_strtolower')?mb_strtolower(trim($value),'UTF-8'):strtolower(trim($value));}
function seoQualityBase(): string {$base=rtrim((string)siteConfigValue('site','base_url',''),'/');if($base===''||normalizedOrigin($base)==='')throw new RuntimeException('SEO quality audit requires a configured public origin.');return $base;}
function seoQualityNoindex(string $robots): bool {return preg_match('/(?:^|,)\s*noindex\s*(?:,|$)/i',$robots)===1;}
function seoQualityExpectedUrl(string $base,string $path): string {if($path==='index.html')return $base.'/';if(str_ends_with($path,'/index.html'))return $base.'/'.substr($path,0,-strlen('index.html'));return $base.'/'.ltrim($path,'/');}
function seoQualityLocalPathFromUrl(string $base,string $url): ?string {
    $parts=parse_url($url);if(!is_array($parts)||isset($parts['query'])||isset($parts['fragment']))return null;$origin=normalizedOrigin($url);if($origin===''||!hash_equals(normalizedOrigin($base),$origin))return null;$path=(string)($parts['path']??'/');if($path===''||$path==='/')return 'index.html';$path=ltrim(rawurldecode($path),'/');return str_ends_with($path,'/')?$path.'index.html':$path;
}
function seoQualitySitemap(string $root,string $base): array {
    $file=$root.'/sitemap.txt';if(!is_file($file))return ['present'=>false,'urls'=>[],'paths'=>[]];$urls=[];$paths=[];foreach(preg_split('/\R/',trim((string)file_get_contents($file)))?:[] as $url){$url=trim($url);if($url==='')continue;$urls[]=$url;$path=seoQualityLocalPathFromUrl($base,$url);if($path!==null)$paths[$path]=$url;}return ['present'=>true,'urls'=>$urls,'paths'=>$paths];
}
function seoQualitySchemaTypes(string $html): array {
    $types=[];if(!preg_match_all('/<script\b[^>]*type=["\']application\/ld\+json["\'][^>]*>(.*?)<\/script>/is',$html,$m))return [];$walk=function($value)use(&$walk,&$types): void {if(!is_array($value))return;if(isset($value['@type']))foreach((array)$value['@type'] as $type)if(is_string($type)&&$type!=='')$types[$type]=true;foreach($value as $child)if(is_array($child))$walk($child);};foreach($m[1] as $raw){$decoded=json_decode(html_entity_decode((string)$raw,ENT_QUOTES|ENT_HTML5,'UTF-8'),true);if(is_array($decoded))$walk($decoded);}return array_keys($types);
}
function seoQualityResolveHref(string $base,string $sourcePath,string $href): ?string {
    $href=html_entity_decode(trim($href),ENT_QUOTES|ENT_HTML5,'UTF-8');if($href===''||$href[0]==='#'||str_starts_with($href,'//'))return null;$scheme=strtolower((string)(parse_url($href,PHP_URL_SCHEME)??''));if($scheme!==''&&!in_array($scheme,['http','https'],true))return null;if($scheme!=='')return seoQualityLocalPathFromUrl($base,preg_replace('/#.*$/','',$href)??$href);
    $clean=preg_replace('/[?#].*$/','',$href)??$href;if($clean==='')return null;if(str_starts_with($clean,'/'))$url=$base.$clean;else{$sourceUrl='/'.($sourcePath==='index.html'?'':(str_ends_with($sourcePath,'/index.html')?substr($sourcePath,0,-strlen('index.html')):$sourcePath));$dir=str_ends_with($sourceUrl,'/')?$sourceUrl:dirname($sourceUrl).'/';$segments=[];foreach(explode('/',$dir.$clean) as $part){if($part===''||$part==='.')continue;if($part==='..'){array_pop($segments);continue;}$segments[]=$part;}$url=$base.'/'.implode('/',$segments);if(str_ends_with($clean,'/'))$url.='/';}return seoQualityLocalPathFromUrl($base,$url);
}
function seoQualityPage(string $root,string $base,string $path,string $label,bool $inSitemap,bool $sitemapPresent): array {
    $full=cmsSafePublicFile($root,$path);if($full===null)return ['path'=>$path,'label'=>$label,'exists'=>false,'issues'=>[seoQualityIssue('missing_page','error','Audited public page does not exist.',$path)]];$html=(string)file_get_contents($full);$title=seoHtmlTitle($html);$description=seoMetaValue($html,'name','description');$robots=seoMetaValue($html,'name','robots');$canonical=seoHtmlCanonical($html);$indexable=!seoQualityNoindex($robots);$issues=[];$tl=function_exists('mb_strlen')?mb_strlen($title,'UTF-8'):strlen($title);$dl=function_exists('mb_strlen')?mb_strlen($description,'UTF-8'):strlen($description);
    if($title==='')$issues[]=seoQualityIssue('missing_title','error','Missing search title.',$path);elseif($tl<10)$issues[]=seoQualityIssue('short_title','warning','Search title is unusually short.',$path,['length'=>$tl]);elseif($tl>65)$issues[]=seoQualityIssue('long_title','warning','Search title may truncate in results.',$path,['length'=>$tl]);
    if($description==='')$issues[]=seoQualityIssue('missing_description','error','Missing meta description.',$path);elseif($dl<50)$issues[]=seoQualityIssue('short_description','warning','Meta description is unusually short.',$path,['length'=>$dl]);elseif($dl>165)$issues[]=seoQualityIssue('long_description','warning','Meta description may truncate.',$path,['length'=>$dl]);
    preg_match_all('/<h1\b/i',$html,$h1);if(count($h1[0])!==1)$issues[]=seoQualityIssue('h1_count','error','Page should expose exactly one H1.',$path,['count'=>count($h1[0])]);
    if($canonical==='')$issues[]=seoQualityIssue('missing_canonical','error','Missing canonical URL.',$path);elseif(seoQualityLocalPathFromUrl($base,$canonical)===null)$issues[]=seoQualityIssue('invalid_canonical','error','Canonical URL is outside the configured public origin or contains unsupported URL state.',$path,['canonical'=>$canonical]);
    if($sitemapPresent&&$indexable&&!$inSitemap)$issues[]=seoQualityIssue('indexable_not_in_sitemap','error','Indexable page is absent from sitemap.txt.',$path);if($sitemapPresent&&!$indexable&&$inSitemap)$issues[]=seoQualityIssue('noindex_in_sitemap','error','Noindex page is advertised in sitemap.txt.',$path);
    $ogMissing=seoMetaValue($html,'property','og:title')===''||seoMetaValue($html,'property','og:description')===''||seoMetaValue($html,'property','og:url')==='';if($ogMissing)$issues[]=seoQualityIssue('open_graph_incomplete','warning','Open Graph metadata is incomplete.',$path);
    if(seoMetaValue($html,'name','twitter:card')===''||seoMetaValue($html,'name','twitter:title')===''||seoMetaValue($html,'name','twitter:description')==='')$issues[]=seoQualityIssue('twitter_incomplete','warning','Twitter/X metadata is incomplete.',$path);
    $schemaTypes=seoQualitySchemaTypes($html);if(!$schemaTypes)$issues[]=seoQualityIssue('schema_missing','warning','Structured data is missing or invalid.',$path);preg_match_all('/<img\b(?![^>]*\balt\s*=)[^>]*>/i',$html,$missingAlt);if(count($missingAlt[0])>0)$issues[]=seoQualityIssue('image_alt_missing','warning','One or more images are missing an alt attribute.',$path,['count'=>count($missingAlt[0])]);preg_match_all('/<a\b[^>]*\bhref\s*=\s*(["\'])(.*?)\1/is',$html,$links,PREG_SET_ORDER);$hrefs=[];foreach($links as $link)$hrefs[]=(string)$link[2];
    return ['path'=>$path,'label'=>$label,'exists'=>true,'inSitemap'=>$inSitemap,'indexable'=>$indexable,'title'=>$title,'description'=>$description,'canonical'=>$canonical,'expectedCanonical'=>seoQualityExpectedUrl($base,$path),'schemaTypes'=>$schemaTypes,'hrefs'=>$hrefs,'issues'=>$issues];
}
function seoQualitySite(string $root,?array $targets=null): array {
    $base=seoQualityBase();$sitemap=seoQualitySitemap($root,$base);$inventory=[];$targets=$targets??seoTargets($root);foreach($targets as $path=>$label)$inventory[(string)$path]=(string)$label;$real=rtrim(str_replace('\\','/',realpath($root)?:$root),'/');foreach(presentationPublicHtmlFiles($root) as $full){$path=ltrim(substr(str_replace('\\','/',$full),strlen($real)),'/');if($path==='')continue;if(!isset($inventory[$path])){$html=(string)file_get_contents($full);$inventory[$path]=seoHtmlTitle($html)?:$path;}}ksort($inventory,SORT_STRING);$pages=[];$siteIssues=[];foreach($inventory as $path=>$label)$pages[$path]=seoQualityPage($root,$base,$path,$label,isset($sitemap['paths'][$path]),$sitemap['present']);
    $titles=[];$descriptions=[];$inbound=array_fill_keys(array_keys($pages),0);foreach($pages as $path=>$page){if(empty($page['exists'])||empty($page['indexable']))continue;$t=seoQualityFold((string)($page['title']??''));$d=seoQualityFold((string)($page['description']??''));if($t!=='')$titles[$t][]=$path;if($d!=='')$descriptions[$d][]=$path;}
    foreach($titles as $paths)if(count($paths)>1){$issue=seoQualityIssue('duplicate_title','error','Duplicate search title across indexable pages.',null,['paths'=>$paths]);$siteIssues[]=$issue;foreach($paths as $path)$pages[$path]['issues'][]=seoQualityIssue('duplicate_title','error','Duplicate search title across indexable pages.',$path,['paths'=>$paths]);}
    foreach($descriptions as $paths)if(count($paths)>1){$siteIssues[]=seoQualityIssue('duplicate_description','warning','Duplicate meta description across indexable pages.',null,['paths'=>$paths]);foreach($paths as $path)$pages[$path]['issues'][]=seoQualityIssue('duplicate_description','warning','Duplicate meta description across indexable pages.',$path,['paths'=>$paths]);}
    foreach($pages as $source=>$page){if(empty($page['exists']))continue;foreach($page['hrefs']??[] as $href){$target=seoQualityResolveHref($base,$source,(string)$href);if($target===null)continue;$full=cmsSafePublicFile($root,$target);if($full!==null){$inbound[$target]=($inbound[$target]??0)+1;continue;}$issue=seoQualityIssue('broken_internal_link','error','Internal link does not resolve: '.$href,$source,['target'=>$target]);$pages[$source]['issues'][]=$issue;$siteIssues[]=$issue;}}
    if($sitemap['present'])foreach($pages as $path=>$page){if($path==='index.html'||empty($page['exists'])||empty($page['indexable'])||!isset($sitemap['paths'][$path]))continue;if(($inbound[$path]??0)===0){$issue=seoQualityIssue('orphan_page','warning','Indexable sitemap page has no internal link from another audited page.',$path);$pages[$path]['issues'][]=$issue;$siteIssues[]=$issue;}}
    $errors=0;$warnings=0;foreach($pages as &$page){$e=count(array_filter($page['issues'],fn($i)=>($i['severity']??'')==='error'));$w=count(array_filter($page['issues'],fn($i)=>($i['severity']??'')==='warning'));$page['score']=max(0,100-$e*20-$w*5);$errors+=$e;$warnings+=$w;}unset($page);foreach($siteIssues as $issue)if(($issue['path']??null)===null){if(($issue['severity']??'')==='error')$errors++;elseif(($issue['severity']??'')==='warning')$warnings++;}
    return ['base'=>$base,'pages'=>$pages,'siteIssues'=>$siteIssues,'summary'=>['pages'=>count($pages),'sitemapUrls'=>count($sitemap['urls']),'errors'=>$errors,'warnings'=>$warnings,'score'=>max(0,100-$errors*5-$warnings)],'sitemap'=>$sitemap];
}
